### ISSUE TITLE
Upgrade to LSP4MP 0.13.0

### ISSUE THREAD

**Issue by mrglavas** [OpenLiberty/liberty-tools-intellij#1057]
See the change log here: https://github.com/eclipse/lsp4mp/blob/master/CHANGELOG.md. The fix for https://github.com/eclipse/lsp4mp/pull/464 is expected to resolve https://github.com/OpenLiberty/liberty-tools-intellij/issues/1016.

**Comment by mrglavas** [comment]
@angelozerr Does this mean the problem with completion being offered after the curly brace (https://github.com/OpenLiberty/liberty-tools-intellij/issues/1016) isn't resolved by LSP4iJ 0.7.0?

**Comment by angelozerr** [comment]
It is fixed. But there is badly a new bug that I have tried to explain.

Sometimes if you have no luck, you loose completion for microprofile-config.properties a very annoying bug.

**Comment by mrglavas** [comment]
Thanks for clarifying. Our build automation is continuously testing LSP4IJ PRs so hopefully this is getting exercised by our automated tests already.

**Comment by mrglavas** [comment]
@angelozerr I noticed that there are Maven artifacts for LSP4MP 0.13.0, 0.13.1 and 0.13.2. I wasn't sure which of these to use so went with 0.13.0 since I see that is currently being pulled in by Quarkus Tools. Since they all look like they were published on the same day I'm wondering if they're all essentially the same release. Do you know what is going on here? The change log https://github.com/eclipse/lsp4mp/blob/master/CHANGELOG.md only mentions 0.13.0.

**Comment by angelozerr** [comment]
> @angelozerr I noticed that there are Maven artifacts for LSP4MP 0.13.0, 0.13.1 and 0.13.2. I wasn't sure which of these to use so went with 0.13.0 since I see that is currently being pulled in by Quarkus Tools. Since they all look like they were published on the same day I'm wondering if they're all essentially the same release. Do you know what is going on here? The change log https://github.com/eclipse/lsp4mp/blob/master/CHANGELOG.md only mentions 0.13.0.

We had some trouble when we have created the release with the CI build. 0.13.0, 1 and 2 are the same.
