### ISSUE TITLE
Start... command to allow users to edit parameters and build file

### ISSUE THREAD

**Issue by kathrynkodama** [OpenLiberty/liberty-tools-intellij#107]
~~Edit the "Start..." command behaviour to allow the user to edit the entire "mvn liberty:dev" command.~~

~~As part of this, use the short-form "mvn liberty:dev" command and relative paths to keep the command short. This applies to the "Start" command as well as "Start..."
From the design:
"Start..." will open an input box with pre-populated mvn liberty:dev command that "Start" runs, allowing users to edit the command as needed, e.g. custom parameters, profiles, etc.~~

See https://github.com/OpenLiberty/liberty-tools-vscode/issues/144

**Comment by TrevCraw** [comment]
New design:

- Allow users to modify custom parameters and the targeted build file.
- Pre populate the input box with `-f <<relative-path-to-build-file>>` ie. `-f ear/pom.xml`
- Update the description of the command to "Specify custom parameters for" `mvn liberty:dev` OR `gradle libertyDev` depending on the type of project.
- Set the working directory of the terminal to the selected project.

**Comment by kathrynkodama** [comment]
For Gradle projects, use the `--project-dir=` option when starting dev mode

**Comment by kathrynkodama** [comment]
@evie-lau Sorry for the late design change, latest design based on discussion with the team:
- Do NOT pre-populate the custom Start... with the build file -f/--project-dir by default.
- Update the description of the command to "Specify custom parameters for" mvn liberty:dev OR gradle libertyDev depending on the type of project.
- Set the working directory of the terminal to the selected project.
