### ISSUE TITLE
Intelij: 2024.2 : Investigate the pop-up warning that leads to the initialization error for UI tests

### ISSUE THREAD

**Issue by vaisakhkannan** [OpenLiberty/liberty-tools-intellij#1087]
As part of supporting IntelliJ version 2024.2, after running the extension, I noticed a warning in both the `runIde` task and `runIdeForUiTests` task in the `Windows` and `Linux` environment, as shown in the images below.  These warnings will lead to initialization failure when running UI tests.

Windows Warning

![Screenshot 2024-11-05 202457 (1)](https://github.com/user-attachments/assets/000a9790-00c1-4e9e-a439-fb6fd12feaa4)

Linux Warning

![Vaishak1](https://github.com/user-attachments/assets/85b61030-d55c-4fcd-9640-3663afde6091)

**Comment by vaisakhkannan** [comment]
For the launcher notification: I had a chat with the JetBrains team on [Slack](https://jetbrains-platform.slack.com/archives/C026SVA9MMM/p1730824524797989), and they made a fix in there upcoming release of Gradle plugin version 2.2.0 to disable the launcher notification on all OS

**Comment by TrevCraw** [comment]
Hi @vaisakhkannan , what is the plan to deal with the other warning, the "Input methods disabler" warning? Can you please display the whole warning in this issue? Should we look into resolving the warning somehow?

**Comment by vaisakhkannan** [comment]
@TrevCraw , This is the "Input methods disabler" warning message 

![image (3)](https://github.com/user-attachments/assets/7b25e4e3-d3ff-4cec-8e96-dc0fdbcc297a)

I am thinking to avoid the warning by using remote robot.

**Comment by vaisakhkannan** [comment]
As part of JetBrains discussion they suggested to use the below code to avoid `native launcher` warning in both linux and windows. So we can keep use gradle plugin version 2.1.0 , and no need to wait for the `2.2.0` release.

This works for me when I tested this on windows, once I confirmed with linux as well , I can raise PR for this

```
intellijPlatformTesting.runIde {
    runIdeForUiTests {
        version = providers.gradleProperty("ideTargetVersion")
        type = IntelliJPlatformType.IntellijIdeaCommunity
        task {
            jvmArgumentProviders.add({
                [
                        "-Drobot-server.port=8082",
                        "-Dide.mac.message.dialogs.as.sheets=false",
                        "-Djb.privacy.policy.text=<!--999.999-->",
                        "-Djb.consents.confirmation.enabled=false",
                        "-Didea.trust.all.projects=true",
                        "-Dide.show.tips.on.startup.default.value=false",
                        "-Dide.mac.file.chooser.native=false",
                        "-DjbScreenMenuBar.enabled=false",
                        "-Dapple.laf.useScreenMenuBar=false",
                ]
            } as CommandLineArgumentProvider)
            systemProperty("ide.native.launcher", "true")
        }
        plugins {
            robotServerPlugin(remoteRobotVersion)
        }
    }
}
```

**Comment by vaisakhkannan** [comment]
There is no issue for ui tests with the second warning present in linux OS.
Once the above fix is merged we can close this issue.
