### ISSUE TITLE
Configure UI tests to run with Java 21 and 2024.2

### ISSUE THREAD

**Issue by TrevCraw** [OpenLiberty/liberty-tools-intellij#1088]
Determine how to parameterize the java target and platform target values and configure those values correctly for the default (production) build and for running the UI tests.
- default (production) build should target Java 17 and the latest 2024.1.* version
- the UI tests build should target Java 21 and the latest 2024.2.* version

**Comment by staicy123** [comment]
Hi @TrevCraw,

We have analyzed the issue and identified two key scenarios based on your description:

Build the Plugin (run buildPlugin task) using IntelliJ 2024.1 and Java version 17
Build and run UI tests (run runIdeForUiTests task) using IntelliJ 2024.2 and Java version 21
Plan of Action:
Scenario 1: Building the plugin (buildPlugin task) with IntelliJ 2024.1 and Java 17 is already complete. A PR has been raised for this implementation: [PR #1053](https://github.com/OpenLiberty/liberty-tools-intellij/pull/1053).
Scenario 2: For building and running UI tests (runIdeForUiTests task) with IntelliJ 2024.2 and Java 21, our analysis is ongoing. We found relevant documentation from JetBrains that suggests the possibility of supporting multiple or different IntelliJ versions in the same project. We are currently working on implementing this based on the guidelines provided in [this JetBrains documentation](https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-testing-extension.html#task). Additionally, we have reached out to JetBrains for further suggestions on handling this specific scenario.
We are continuing with the implementation for Scenario 2 and will update you as soon as we have more information.

Thanks
