### ISSUE TITLE
Add run and debug config

### ISSUE THREAD

**Issue by TrevCraw** [OpenLiberty/liberty-tools-intellij#110]
Prototype both run and debug configuration for IntelliJ.

For debug config, see if it is possible to integrate with the current remote Java debug config. Try to dynamically pick up the Liberty debug port from `server.env` in target when the debug configuration is created OR when the debug action is run.

If the port cannot be found or the debugger fails to attach, try to provide a more helpful Liberty-centric error message (ie. suggest that Liberty dev mode may not be running).

Anticipated user flow would be to start Liberty dev mode and then start the debug action once dev mode is running.

**Comment by kathrynkodama** [comment]
Some prototyping started here: https://github.com/kathrynkodama/open-liberty-tools-intellij/tree/run-debug-config
