### ISSUE TITLE
Intellij 2024.2: Extra Dialog Appears for Liberty Toolbar Actions for Multiple projects

### ISSUE THREAD

**Issue by vaisakhkannan** [OpenLiberty/liberty-tools-intellij#1131]
Identified a behavioural difference in DevMode actions from the Liberty Tool window between IntelliJ versions `2024.1` and `2024.2` (the same behaviour is observed in 2024.3 as well).

An extra pop-up window appears to select the Liberty project, even though the dev mode of the corresponding project is already selected.

I found this behavior in the code of the feature branch `intellij-2024.2-support-backup`.

Behaviour in Intellij `2024.1`

https://github.com/user-attachments/assets/bf61cdd4-e3ab-432e-ab40-56c67f6a40ce

Behaviour in Intellij `2024.2`

https://github.com/user-attachments/assets/d33bb33b-d61e-4eac-9970-043175232c81

NOTE: Same project is tested in both intellij versions. 
The behaviour was observed today when I checked on Windows as part of the support Intellij 2024.3 FVT. Then, I checked on Mac with IntelliJ version 2024.2, and the same issue was present. During the initial FVT, we tested on Mac, where the project setup was specified as "Mac: generate projects to different folders." This is why we didn’t notice the issue at that time.

**Comment by vaisakhkannan** [comment]
I observed a strange behavior: if we perform a right-click action on the project name and select the Liberty Dev Mode action, it executes properly. After this, everything works as expected. From the next time onward, the Liberty action performs correctly using the Liberty Play button without requiring the project to be selected, and no popup dialog appears.

To reproduce the issue again, uninstall the zip file and then reinstall it.

https://github.com/user-attachments/assets/2afeae90-2294-49c6-b966-c45106eb8ccb

**Comment by anusreelakshmi934** [comment]
> I observed a strange behavior: if we perform a right-click action on the project name and select the Liberty Dev Mode action, it executes properly. After this, everything works as expected. From the next time onward, the Liberty action performs correctly using the Liberty Play button without requiring the project to be selected, and no popup dialog appears.
> 
> To reproduce the case mentioned in this issue again, uninstall the zip file and then reinstall it.
> 
>  Strange-behaviour.mov

I tried this scenario in linux too. It is reproducible

**Comment by vaisakhkannan** [comment]
As part of debugging the code, We found in the line https://github.com/OpenLiberty/liberty-tools-intellij/blob/367e2008034b2910a604394e26e84113e8bc702b/src/main/java/io/openliberty/tools/intellij/actions/LibertyGeneralAction.java#L58 having `buildFile` null. 

Then one more thing when I try to build the code for production with the intellij version 2024.3, I can see the deprecated warning in the above shared line. So we should fix the deprecated failures  I guess.

```
./gradlew buildPlugin

> Task :verifyPluginProjectConfiguration
[org.jetbrains.intellij.platform] The following plugin configuration issues were found:
- The since-build='241' is lower than the target IntelliJ Platform major version: '243'.
- The Java configuration specifies sourceCompatibility='17' but IntelliJ Platform '2024.3' requires sourceCompatibility='21'.
- The dependency on the Kotlin Standard Library (stdlib) is automatically added when using the Gradle Kotlin plugin and may conflict with the version provided with the IntelliJ Platform, see: https://jb.gg/intellij-platform-kotlin-stdlib

> Task :compileJava
/Users/vaisakht/Documents/DEVEX/intellij/repos/liberty-tools-intellij/src/main/java/io/openliberty/tools/intellij/runConfiguration/LibertyRunConfiguration.java:142: warning: [removal] getData(String) in DataContext has been deprecated and marked for removal
        DataContext dataCtx = dataId -> {
                              ^
/Users/vaisakht/Documents/DEVEX/intellij/repos/liberty-tools-intellij/src/main/java/io/openliberty/tools/intellij/runConfiguration/LibertyRunConfiguration.java:152: warning: [removal] AnActionEvent(InputEvent,DataContext,String,Presentation,ActionManager,int) in AnActionEvent has been deprecated and marked for removal
        AnActionEvent event = new AnActionEvent(null, dataCtx, ActionPlaces.UNKNOWN, new Presentation(), ActionManager.getInstance(), 0);
                              ^
/Users/vaisakht/Documents/DEVEX/intellij/repos/liberty-tools-intellij/src/main/java/io/openliberty/tools/intellij/LibertyExplorer.java:366: warning: [removal] AnActionEvent(InputEvent,DataContext,String,Presentation,ActionManager,int) in AnActionEvent has been deprecated and marked for removal
                action.actionPerformed(new AnActionEvent(null,
                                       ^
/Users/vaisakht/Documents/DEVEX/intellij/repos/liberty-tools-intellij/src/main/java/io/openliberty/tools/intellij/actions/LibertyGeneralAction.java:58: warning: [removal] getData(String) in DataContext has been deprecated and marked for removal
        VirtualFile buildFile = (VirtualFile) e.getDataContext().getData(Constants.LIBERTY_BUILD_FILE);
                                                                ^
/Users/vaisakht/Documents/DEVEX/intellij/repos/liberty-tools-intellij/src/main/java/io/openliberty/tools/intellij/actions/RunLibertyDevTask.java:87: warning: [removal] AnActionEvent(InputEvent,DataContext,String,Presentation,ActionManager,int) in AnActionEvent has been deprecated and marked for removal
                                    action.actionPerformed(new AnActionEvent(null, DataManager.getInstance().getDataContext(libertyTree), e.getPlace(), e.getPresentation(), ActionManager.getInstance(), 0));
                                                           ^
/Users/vaisakht/Documents/DEVEX/intellij/repos/liberty-tools-intellij/src/main/java/io/openliberty/tools/intellij/actions/RunLibertyDevTask.java:123: warning: [removal] AnActionEvent(InputEvent,DataContext,String,Presentation,ActionManager,int) in AnActionEvent has been deprecated and marked for removal
                action.actionPerformed(new AnActionEvent(null, e.getDataContext(), e.getPlace(), e.getPresentation(), ActionManager.getInstance(), 0));
                                       ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
6 warnings

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.7/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD SUCCESSFUL in 3s
13 actionable tasks: 13 executed

```
