### ISSUE TITLE
Rename package to "io.openliberty.tools"

### ISSUE THREAD

**Issue by kathrynkodama** [OpenLiberty/liberty-tools-intellij#114]
On the ls-integration branch(https://github.com/OpenLiberty/liberty-tools-intellij/tree/ls-integration/src/main/java), rename "com.langserver.devtools" to "io.openliberty.tools"

**Comment by javamultiplex** [comment]
@kathrynkodama  - I would like to work on this. Can you please assign this issue to me?

**Comment by kathrynkodama** [comment]
@javamultiplex Thank you, we require any external contributors to follow the DCO, defined here: https://github.com/OpenLiberty/liberty-tools-intellij/blob/main/CONTRIBUTING.md#legal

**Comment by kathrynkodama** [comment]
Closed with #115 and https://github.com/OpenLiberty/liberty-tools-intellij/pull/124
