### ISSUE TITLE
Clarify comment in UIBotTestUtils added for 2024.3

### ISSUE THREAD

**Issue by turkeylurkey** [OpenLiberty/liberty-tools-intellij#1152]
In UIBotTestUtils we find the comment 

```
        // Report the last error if there is one and avoid throwing a RuntimeException for the "Close All Tabs" action,
        // as it is not always necessary for at least one tab to be open in the Editor Window in certain cases.
```
Could you improve this comment by describing the problem and the solution?

**Comment by vaisakhkannan** [comment]
@turkeylurkey , I have updated the comment [here](https://github.com/OpenLiberty/liberty-tools-intellij/blob/1d60470f97f74334a9282acd14af69040d6d9f34/src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java#L1696C9-L1703C12)

Could you check and suggest the changes? please let me know if the comment is not clear to you
Thanks

**Comment by turkeylurkey** [comment]
Yes, that seems like a good explanation, thank you.
