### ISSUE TITLE
Set up Jenkins process for code signing

### ISSUE THREAD

**Issue by TrevCraw** [OpenLiberty/liberty-tools-intellij#116]
We need to sign the artifacts for this project as part of our build process.
Example for the Liberty Config Language Server can be found here: https://hyc-liberty-tools-team-jenkins.swg-devops.com/job/liberty-language-server-signing/configure

**Comment by AnuRam123** [comment]
Completed the codesigning for intellij and vscode artifacts:
1. https://hyc-liberty-tools-team-jenkins.swg-devops.com/job/liberty-tools-intellij-build-code-sign/
2. https://hyc-liberty-tools-team-jenkins.swg-devops.com/job/liberty-tools-vscode-build-code-sign/

The scripts to sign and verify the code is found in the VM
