### ISSUE TITLE
Project pop up menu actions prompt a user to select a project instead of running directly from the project selected in the UI.

### ISSUE THREAD

**Issue by mrglavas** [OpenLiberty/liberty-tools-intellij#126]
Steps to reproduce:

1) Right click a project from the Liberty explorer window.

![image](https://user-images.githubusercontent.com/890521/200856039-d42b8b4a-3e4a-418e-ab9e-518502fca259.png)

2) Select an action.

Instead of running the action against the selected project, the user is prompted to choose a project from a dialog which pops up.

![image](https://user-images.githubusercontent.com/890521/200856345-10bfe61e-97fa-4811-9106-27471a2f6b38.png)

Seems like the context isn't being set on this path. Prior to the introduction of the shift + shift support, I believe this probably failed with an error.

**Comment by TrevCraw** [comment]
Update - I am now seeing this error again - it seems to be intermittent in my environment. I think having multiple IntelliJ windows open affects the behaviour.

When I have one IntelliJ window open, I run into this error the first time I try to use the right click pop up menu to run dev mode on a project. The second time I right click to run dev mode, it runs automatically. However, there is a new issue with this. If I right click to run a project, it will run automatically in the root directory of whatever the last project to run was. For example, using the https://github.com/OpenLiberty/guide-reactive-rest-client - I right click to run the `query` project in dev mode and that runs as expected. Then I right click to run the `system` project, and dev mode still runs from the `query` directory.

**Comment by TrevCraw** [comment]
Update: When opening a second IntelliJ window and using the right click pop up menu to run the "Start" action, the last run app will start up, even if that last run app is in the other window.

**Comment by TrevCraw** [comment]
https://github.com/OpenLiberty/liberty-tools-intellij/pull/408 fixes the issue where the last run project is always run when using the right click method to start dev mode. However, it seems to reintroduce the original error we saw in this issue where right click prompts the user to select a project when there is no need to (ie. the tools should know which project to run against based on which project was clicked on). It should be noted that once an action has been run once through another method (ie. double click in the drop down menu) , then the project prompt goes away for that particular action in the right click menu. All other actions that have not been run yet through another method will still prompt.
