### ISSUE TITLE
Action executed from shift + shift window may use context from cancelled action.

### ISSUE THREAD

**Issue by mrglavas** [OpenLiberty/liberty-tools-intellij#127]
Steps to reproduce:

1) Select "Start dev mode..." from the project window.

![image](https://user-images.githubusercontent.com/890521/200861911-2935c4f6-ce3d-41ce-bf63-2e97ea32d1e5.png)

2) Select "Cancel" from the pop up dialog.

![image](https://user-images.githubusercontent.com/890521/200862299-54e1086c-9b36-4047-bd17-42d0f9c0047b.png)

3) Press shift + shift and select an action to run.

![image](https://user-images.githubusercontent.com/890521/200862793-6b8bfe2a-f9ce-4e4e-aa7a-2ef65bf7a5be.png)

Instead of prompting the user to select a project for the action, the action runs with the project that had been selected for the previously cancelled action.

**Comment by mrglavas** [comment]
Might be related to: https://github.com/OpenLiberty/liberty-tools-intellij/issues/126.

**Comment by kathrynkodama** [comment]
Just adding that I see the same behaviour @TrevCraw
