### ISSUE TITLE
Manually add/remove projects to/from Liberty tool window through "shift + shift" window

### ISSUE THREAD

**Issue by TrevCraw** [OpenLiberty/liberty-tools-intellij#128]
When a user uses the "shift + shift" menu, there should be options to "Add new Liberty project to Liberty tool window" and "Remove Liberty project from Liberty tool window"
- If "Add" is selected, users should be presented with projects/build files in the workspace that have not been detected by the Liberty tool window.
  - When users select a project/build file, that project should be added to the Liberty tool window.
- If "Remove" is selected, users should at least be presented with projects/build files that have been manually added to the Liberty tool window. If automatically detected projects can be added as options for removal, that's even better, but not required.
  - When users select a project/build file, that project should be removed from the Liberty tool window.

**Comment by mrglavas** [comment]
@TrevCraw If the list of available projects to add or remove is empty what should the behaviour be?
