### ISSUE TITLE
Pull in latest bug fixes to JDT LS ext components from Eclipse LSP4Jakarta and LSP4MP

### ISSUE THREAD

**Issue by kathrynkodama** [OpenLiberty/liberty-tools-intellij#161]

**Comment by turkeylurkey** [comment]
LSP4MP fixes from version [0.5.0](org.eclipse.lsp4mp:org.eclipse.lsp4mp.ls:0.5.0) already pulled in.
LSP4Jakarta: checked fixes made since Aug 4 and all have been pulled into this IntelliJ plugin.
