### ISSUE TITLE
Project with multi modules is showing all modules with same name [Gradle]

### ISSUE THREAD

**Issue by fabio-franco** [OpenLiberty/liberty-tools-intellij#182]
When using the liberty-bikes project (https://github.com/OpenLiberty/liberty-bikes), that is a multi-module project, Intellij is showing all the modules with the same name, which can confuse the end-user. See the image below:

![image](https://user-images.githubusercontent.com/7606936/204633412-34dd8260-edcf-4ded-80a4-f942f49acf7f.png)

A suggestion, in case of gradle, is to use the name inside the `build.grade` file.

**Comment by kathrynkodama** [comment]
We should be using the name of the parent directory of the build.gradle file, not the project's directory name.
