### ISSUE TITLE
Go-to feature does not work with language servers

### ISSUE THREAD

**Issue by evie-lau** [OpenLiberty/liberty-tools-intellij#192]
Probably related to #147 with some language server features not working in our plugin.
The go-to feature doesn't work for linked properties or files (ctrl/cmd+click on a linked file or definition).

LCLS with server.xml - defining an `<include location="somexmlfile">`
![image](https://user-images.githubusercontent.com/689163/205751179-ded116fa-d9dc-4ff7-bfca-6c5cb16eca98.png)

LSP4MP with `ConfigProperty` - pointing to a property defined in `microprofile-config.properties`
![image](https://user-images.githubusercontent.com/689163/205751273-88809810-ce43-470a-b660-5a133f4d863d.png)
![image](https://user-images.githubusercontent.com/689163/205751292-40ed7109-4432-4f44-bca4-f1240df1303a.png)

**Comment by evie-lau** [comment]
Somehow, removing these lines gets it working for microprofile. 
https://github.com/OpenLiberty/liberty-tools-intellij/blob/2908d53a16704abbb812a4afb6095e9e3907d58e/src/main/resources/META-INF/lsp.xml#L40-L44

Seems like there is another implementation for activating LSP4MP on microprofile-config.properties files via:
https://github.com/OpenLiberty/liberty-tools-intellij/blob/2908d53a16704abbb812a4afb6095e9e3907d58e/src/main/resources/META-INF/plugin.xml#L87
https://github.com/OpenLiberty/liberty-tools-intellij/blob/2908d53a16704abbb812a4afb6095e9e3907d58e/src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/internal/core/providers/MicroProfileConfigSourceProvider.java#L86-L90

**Comment by evie-lau** [comment]
Disabled by #217 because the goto handler implementation kept triggering NPEs, even when it wasn't working properly.

**Comment by kathrynkodama** [comment]
Updating to document that as of now, Ctrl + Click on a reference to a local definition does not work from Eclipse in Java files:
![image](https://user-images.githubusercontent.com/26146482/213256526-c8b1b0b5-3438-430e-9e7e-3c76d4a1533b.png)

Ctrl + Click on a `@ConfigProperty` does work, it navigates to the corresponding config property in the microprofile-config.properties file 
![image](https://user-images.githubusercontent.com/26146482/213256863-9763714f-24c6-4ffe-bc1a-5a625d2da818.png)

**Comment by angelozerr** [comment]
Fir the first issue with xml it is because 
ksp documentLink is not supported in IJ. I plan to work on it

**Comment by angelozerr** [comment]
> Updating to document that as of now, Ctrl + Click on a reference to a local definition does not work from Eclipse in Java files OR microprofile-config.properties files:

Please see the fix at https://github.com/redhat-developer/intellij-quarkus/pull/866

**Comment by angelozerr** [comment]
Just for your information, I'm working to support `textDocument/documentLink` in the issue https://github.com/redhat-developer/intellij-quarkus/issues/832 I created a draft PR https://github.com/redhat-developer/intellij-quarkus/pull/901

**Comment by anusreelakshmi934** [comment]
Update - Tested Using the latest version of LSP4IJ 
Ctrl + Click on a reference to a local definition does work in Java files and microprofile-config.properties files:
Attaching Screen records below :

https://github.com/OpenLiberty/liberty-tools-intellij/assets/141303561/a8669b2a-d012-47c7-87e5-0e3c63ebeb7b

https://github.com/OpenLiberty/liberty-tools-intellij/assets/141303561/01817e05-a9b6-41ec-8aaa-c30ac8e0ea10


Also Ctrl + Click on a @ConfigProperty navigates to the corresponding entry in the microprofile-config.properties file, and vice versa: Ctrl + Click on a property in microprofile-config.properties navigates to its definition in the Java code.


https://github.com/OpenLiberty/liberty-tools-intellij/assets/141303561/778c7687-ebda-42fe-83ec-c22e544cc155
