### ISSUE TITLE
Need to update ls-integration layer to line up with LSP4MP 0.6.0

### ISSUE THREAD

**Issue by AnuRam123** [OpenLiberty/liberty-tools-intellij#194]
Platform : Mac
IntelliJ version: IntelliJ IDEA 2022.2.3 (Community Edition)

This surfaces as issues while create a file with jaxrc snippets for gradle project
<img width="481" alt="image" src="https://user-images.githubusercontent.com/5245907/205755600-1852bb05-0142-4a39-bb26-1c3ac8f303d6.png">
version in build.gradle
```
dependencies {
    // provided dependencies
    providedCompile 'jakarta.platform:jakarta.jakartaee-api:8.0.0' 
    providedCompile 'org.eclipse.microprofile:microprofile:4.1' 

}
```
version in pom.xml
```
dependency>
            <groupId>org.eclipse.microprofile</groupId>
            <artifactId>microprofile</artifactId>
            <version>5.0</version>
            <type>pom</type>
            <scope>provided</scope>
        </dependency>
```

**Comment by evie-lau** [comment]
@dshimo and I have completed pulling in the changes to support LSP4MP 0.6.0, and seems to mostly be in line with Intellij-Quarkus with code action/quickfix support. 
We've noticed a few issues, most of which are also present in the Quarkus Tools plugin.
- duplicate diagnostics (from `LSPLocalInspectionTool` and `LSPCodeActionAnnotator`)
- reintroduce diagnostic sync issues (from the diagnostics provided via `<externalAnnotator>` which uses the new `LSPCodeActionAnnotator` class, which has similar logic to the `checkFile` method currently have to force rerun to fix syncing)
- some quickfixes don't work - currently debugging to see why

**Comment by turkeylurkey** [comment]
I opened issues to track the problems and added these to the Epic #280.
```
duplicate diagnostics (from LSPLocalInspectionTool and LSPCodeActionAnnotator)
reintroduce diagnostic sync issues (from the diagnostics provided via <externalAnnotator> which uses the new LSPCodeActionAnnotator class, which has similar logic to the checkFile method currently have to force rerun to fix syncing) 
```
