### ISSUE TITLE
Terminal focus doesn't shift and terminal renaming doesn't work 

### ISSUE THREAD

**Issue by kathrynkodama** [OpenLiberty/liberty-tools-intellij#198]
When we run on a Liberty action on a project, the focus is not automatically pulled to the corresponding terminal window for the project (if it was not already there) even though we set visible and request focus:
https://github.com/OpenLiberty/liberty-tools-intellij/blob/2908d53a16704abbb812a4afb6095e9e3907d58e/src/main/java/io/openliberty/tools/intellij/actions/LibertyGeneralAction.java#L182-L183

Also noting that terminal renaming doesn't work, issue open against JetBrains:  https://youtrack.jetbrains.com/issue/IDEA-297207

See https://github.com/OpenLiberty/liberty-tools-intellij/issues/143#issuecomment-1319348592

Blocked on fixing this until we have the API fixes from Jetbrains

**Comment by TrevCraw** [comment]
Dependent on https://github.com/OpenLiberty/liberty-tools-intellij/issues/505
