### ISSUE TITLE
Add explanation/instructions to empty tool window

### ISSUE THREAD

**Issue by kathrynkodama** [OpenLiberty/liberty-tools-intellij#220]
See https://github.com/OpenLiberty/liberty-tools-eclipse/issues/294

**Comment by Rahul-Biju** [comment]
@TrevCraw 
Below is what i propose should be displayed in the Liberty Dashboard when no projects are available:
1. If no projects are open in the Intellij Explorer, open or create a Liberty project using the File menu. 
 2. If there is one or more existing Maven or Gradle projects open in the Intellij Explorer, try one of the following: 
 
 	- Configure the Liberty build plugin in the build file of an existing Maven or Gradle project.
 	- Add a server.xml file to an existing Maven or Gradle project at 'src/main/liberty/config'.
 	- Manually add an existing Maven or Gradle project to the Liberty Dashboard through the Intellij Explorer command palette action 'Liberty:'Add project to Liberty Dashboard'
