### ISSUE TITLE
Empty dropdown when trying to add a Gradle project using shift-shift on Windows

### ISSUE THREAD

**Issue by fabio-franco** [OpenLiberty/liberty-tools-intellij#228]
For this test, I used liberty-bikes project. This issue may be related to this issue https://github.com/OpenLiberty/liberty-tools-intellij/issues/182, that is, the fact that liberty-bikes inside IntelliJ is showing all the project with the same label:

<img width="145" alt="image" src="https://user-images.githubusercontent.com/7606936/207698993-7067f157-6182-486d-a695-c038bacf9d53.png">

To reproduce the issue, I renamed the "config" folder in the `player-service` and then it correctly disappeared from the menu. However, when clicking on shift-shift to add the project again, after I chose "Add Project to selected window", and then it appeared a dropdown with an empty select option:

<img width="273" alt="image" src="https://user-images.githubusercontent.com/7606936/207681216-ea02b8c4-a627-4521-a491-5bea5cb68935.png">

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/7606936/207680204-33f32420-c086-4414-82fa-e2596b636521.png">

**Comment by TrevCraw** [comment]
Attempt to reproduce with multiple single module projects under same folder.

**Comment by TrevCraw** [comment]
Closed as part of https://github.com/OpenLiberty/liberty-tools-intellij/pull/263
