### ISSUE TITLE
Cursor placement in server.xml should be between open and closing tag

### ISSUE THREAD

**Issue by kathrynkodama** [OpenLiberty/liberty-tools-intellij#260]
For example, after inserting the feature from LemMinX Liberty ext, the cursor placement is at the end of the line:
<img width="372" alt="image" src="https://user-images.githubusercontent.com/26146482/216660998-31fe510a-af33-4e92-a2f6-a921169a9db2.png">

Instead it would be more help in between the open and closing tag:
<img width="434" alt="image" src="https://user-images.githubusercontent.com/26146482/216661165-1a3a3f0b-2aae-43f6-b992-9563a4baebfd.png">

**Comment by angelozerr** [comment]
It is because LSP client for IJ doesn't completion support. I plan to work on it https://github.com/redhat-developer/intellij-quarkus/issues/786

**Comment by angelozerr** [comment]
I suggest too that liberty lemminx extension return as choice the list of features.

Once completion item woll be applied it will open à second popup with features list.

It will work on eclipse ide and vscode. For IJ it requires to support completion snippet. I plan to work on it

**Comment by anusreelakshmi934** [comment]
https://github.com/OpenLiberty/liberty-tools-intellij/assets/141303561/97672f8d-9272-4ddf-8279-c70e101c3ba1


Using the Latest Lsp4ij version this is no longer reproducible. The cursor placement is now in between the open and closing tag
