### ISSUE TITLE
Liberty Lemminx ext: multiple diagnostics on same element, only first diagnostic is shown in problems view and on hover

### ISSUE THREAD

**Issue by kathrynkodama** [OpenLiberty/liberty-tools-intellij#268]
Adding `<include location="some_location.xml">` to a server.xml, we expect 2 diagnostics back from the Liberty LemMinX ext:
1) The specified resource cannot be skipped. Check location value or add optional attribute.
2) The resource at the specified location could not be found.

However, only the first appears in the UI and the problems view:

![image](https://user-images.githubusercontent.com/26146482/219715609-04a72d76-b908-42f5-946a-a18831d6ce49.png)

We can see both diagnostics returned as `problemDescriptors` in the `LSPInspectionTool#checkFile()` method, but only the first one shows up in the UI.
https://github.com/OpenLiberty/liberty-tools-intellij/blob/6bf699c9fe5d23fcb96d35caebceeaf3a1db3161/src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/operations/diagnostics/LSPLocalInspectionTool.java#L92
Attaching a debugger, here is `problemDescriptors.toString()`:
```
problemDescriptors: [The specified resource cannot be skipped. Check location value or add optional attribute., The resource at the specified location could not be found.]
```

Seems specific to Liberty Lemminx, tried the same case with Eclipse LSP4Jakarta, here is an example of 2 diagnostics returned on the same element as expected.
![image](https://user-images.githubusercontent.com/26146482/219716120-d111146a-081e-4627-bc4a-a28804889b3d.png)

**Comment by evie-lau** [comment]
After some testing, it seems like when all these conditions are met, only the Error diagnostic will show, and the problem descriptor for the Warning will be ignored.

1. both diagnostics (error and warning) have the same range
2. both diagnostics come from the same language server

Seems like this may be built into the IntelliJ design of their LocalInspectionTool logic.

Also confirmed this same behavior with LSP4Jakarta in our plugin, and LSP4MP in Quarkus Tools plugin.

**Comment by evie-lau** [comment]
Asked in the JetBrains Platform about this behavior, and they confirmed that this occurs when there are overlapping problem descriptors of different severity.

**Comment by evie-lau** [comment]
Wondering if this may be insightful for us, if we still want to pursue having multiple severity level highlights. This thread may be a slightly different scenario though.
https://intellij-support.jetbrains.com/hc/en-us/community/posts/360010576900-Missing-highlight-when-multiple-annotators-applied-to-same-TextRange-
