### ISSUE TITLE
Running start from "shift shift" menu does not work correctly with multiple IntelliJ windows open

### ISSUE THREAD

**Issue by TrevCraw** [OpenLiberty/liberty-tools-intellij#271]
Using [getting started guide](https://github.com/openliberty/guide-getting-started) and [mp-health guide](https://github.com/openliberty/guide-microprofile-health) (with the `start` directory removed, so there is only one Liberty project)

1. Open the getting started guide - both "start" and "finish" projects should be loaded
2. Run `Liberty: Start` from "shift shift" menu - this should run as expected
3. Open (File->Open) the mp-health guide project and select "New Window" - there should now be two IntelliJ windows
4. In the 2nd window (with the mp health guide), Run `Liberty: Start` from "shift shift" menu - this is when the error occurs - IntelliJ will open up the project dialog selection in the 1st window for the getting started guide - the expected behaviour would be that the "shift shift" action applies to the window that the user was in when opening the "shift shift" menu.
5. If you run the "Start" action from the Liberty Tool window for the mp-health guide in the 2nd IntelliJ window, it will run as expected, and then the "shift shift" menu start bug will go away for the 2nd IntelliJ window - however, the bug now occurs in reverse. If you go back to the 1st IntelliJ window and try to use the "shift shift" menu to select `Liberty: Start`, it will run the mp-health app in the 2nd IntelliJ window.

**Comment by evie-lau** [comment]
May be fixed by #408?
