### ISSUE TITLE
AlreadyDisposedException using "Liberty: Start" from the "shift shift" menu after opening new project in "This Window"

### ISSUE THREAD

**Issue by TrevCraw** [OpenLiberty/liberty-tools-intellij#272]
Using [getting started guide](https://github.com/openliberty/guide-getting-started) and [mp-health guide](https://github.com/openliberty/guide-microprofile-health) (with the `start` directory removed, so there is only one Liberty project)

1. Open the mp-health guide
2. Run `Liberty: Start` from the "shift shift" menu or run "Start" from the Liberty Tool Window - this should run as expected
3. Open (File->Open) the getting started guide project and select "This Window" - the getting started guide should now be open in IntelliJ and the mp-health guide no longer there.
4. Run `Liberty: Start` from the "shift shift" menu - this is when the `AlreadyDisposedException` occurs and the app does not run
5. Subsequent attempts to run `Liberty: Start` from the "shift shift" menu do not result in an exception, but the app still does not run
6. Running "Start" from Liberty Tool Window is successful and resolves this issue - you can now run the project from the "shift shift" menu

If two projects were loaded initially (ie. "start" and "finish"), then the selection dialog in the "shift shift" menu will be populated with the previous open projects. Selecting a project to run results in an `AlreadyDisposedException`. This can be reproduced by opening the getting started guide first and then the mp-health guide.

**Comment by kathrynkodama** [comment]
See https://github.com/OpenLiberty/liberty-tools-intellij/pull/207, likely some reference to the project object that no longer exists but is still being referenced.

**Comment by TrevCraw** [comment]
@mezarin discovered that this bug also occurs when trying to run the "Start" action using the "right-click" pop up menu.

https://github.com/OpenLiberty/liberty-tools-intellij/issues/126 and https://github.com/OpenLiberty/liberty-tools-intellij/issues/271 are probably related.

From @mezarin , current suspicion is action objects are caching data and objects are not being released or old references are being held onto.

**Comment by TrevCraw** [comment]
@mezarin also discovered that this bug occurs when selecting an action in the Liberty Tool Window and then clicking the green run button in the Liberty Tool Window toolbar.
