### ISSUE TITLE
LS Integration: XML comment diagnostics forces document into a broken state

### ISSUE THREAD

**Issue by kathrynkodama** [OpenLiberty/liberty-tools-intellij#275]
**To reproduce**
1. Open to a server.xml file
2. Comment out a line - I used the keyboard shortcut <kbd>Cmd</kbd> + <kbd>/</kbd>.Diagnostic appears on the next comment in the document indicating that "The string "--" is not permitted within comments." In the screenshot below, I used the keyboard shortcut to comment out line 15, the diagnostic appeared on the comment on line 17.
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/26146482/221915703-3fead37d-6851-4e2a-82ad-19fb0e81e78e.png">
3. Enter into a broken state, switching windows does not correct the issue. 

Able to reproduce on Mac, Linux and Windows.

**Comment by evie-lau** [comment]
Found another scenario which seems to narrow it down to a text "replacement" triggering the broken state.
I tried highlighting and replacing a valid feature with some other text, and the line gets read as the new text prepended to the replaced text.
Example: Highlighted and replaced the feature text `microProfile-5.0` with `a`:
![image](https://user-images.githubusercontent.com/689163/222225799-b1de1fa6-3d20-4e79-9a92-14ba4f2a6acb.png)


Forcing `TextDocumentSyncKind.Full` in the IntelliJ Client seemed to fix this issue and the comment shortcut issue, which I think may essentially be a text replace as well.

**Comment by kathrynkodama** [comment]
@evie-lau Your thoughts led me to https://github.com/OpenLiberty/liberty-tools-intellij/blob/54632ee3d31edebeeeb8a2d722471593a66592bf/src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/DocumentContentSynchronizer.java#L94-L103

when I comment out a line, the change params are: 
```
DidChangeTextDocumentParams [
  textDocument = VersionedTextDocumentIdentifier [
    version = null
    uri = "file:///Users/kathrynkodama/devex/sampleProjects/guide-getting-started/finish/src/main/liberty/config/server.xml"
  ]
  uri = null
  contentChanges = SingletonList (
    TextDocumentContentChangeEvent [
      range = Range [
        start = Position [
          line = 10
          character = 0
        ]
        end = Position [
          line = 10
          character = 0
        ]
      ]
      rangeLength = 0
      text = "<!--"
    ]
  )
]
``` 

The new text noted is only `<!--` with no secondary change event for the end of the comment `-->`. It's either missing the second change event because both changes are applied at once, or both changes should be in the one change event.

**Comment by kathrynkodama** [comment]
> Example: Highlighted and replaced the feature text microProfile-5.0 with a:

Taking this example of replacing a feature block with the letter 'a' in a server.xml. Here is the `textDocument/didChange' parameters LemMinX receives from VS Code: 

```
[Trace - 1:45:36 PM] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "uri": "file:///Users/kathrynkodama/devex/sampleProjects/guide-getting-started/finish/src/main/liberty/config/server.xml",
        "version": 6
    },
    "contentChanges": [
        {
            "range": {
                "start": {
                    "line": 7,
                    "character": 17
                },
                "end": {
                    "line": 7,
                    "character": 29
                }
            },
            "rangeLength": 12,
            "text": "a"
        }
    ]
}
```
and here is the exact same change in IntelliJ: 

```
2023-03-01 13:47:48,071 [  34340]   WARN - i.o.t.i.l.l.LanguageServerWrapper - NotificationMessage
{
  "jsonrpc": "2.0",
  "method": "textDocument/didChange",
  "params": {
    "textDocument": {
      "version": 2,
      "uri": "file:///Users/kathrynkodama/devex/sampleProjects/guide-getting-started/finish/src/main/liberty/config/server.xml"
    },
    "contentChanges": [
      {
        "range": {
          "start": {
            "line": 7,
            "character": 17
          },
          "end": {
            "line": 7,
            "character": 17
          }
        },
        "rangeLength": 0,
        "text": "a"
      }
    ]
  }
}

```
Notice the difference in ranges, IntelliJ passes just the index changed: [17,17] but VS Code passes the whole range for the replaced text: [17,29]

**Comment by kathrynkodama** [comment]
Noting as it may be a symptom of the same problem? 
Intermittently replacing text with a completion item eats the rest of the line's content:
![image](https://user-images.githubusercontent.com/26146482/222259283-d7c89601-8b0b-49ce-aa9c-71f1d09fe6c6.png)

![image](https://user-images.githubusercontent.com/26146482/222259527-708f8926-e040-4d40-bd91-8b44bfaa9c82.png)

**Comment by evie-lau** [comment]
From debugging, it seems that text replacement registers as two separate events: 1) deletion of the original text, 2) insertion of the new text.

It seems that IntelliJ runs the `beforeDocumentChange` and `documentChanged` methods for both of them, and tried to send the data off to send them off (to PsiDocumentManager -> run `sendDidChangeEvent` -> send off to LS)
But `sendDidChangeEvent` seems to run async due to the PsiDocumentManager dealing with it. By the time the method runs, the `changeParams` had already been processed for both events (second event replaced first event), so only the last event occurs.

**Comment by evie-lau** [comment]
Seems to be happening again. Details originally documented [here](https://github.com/OpenLiberty/liberty-tools-intellij/pull/320#issuecomment-1490607703), important details below.
> Potentially a timing/race condition for the doc changes being applied to the editor, and the accept diagnostics code getting the latest copy of the document.
> Some example scenarios that happened:
> - had location="test1.xml", highlighted location, typed a -> read n is not allowed in element 'include'
> - had b="text1.xml" , highlighted b, typed location -> read bocation is not allowed...
>
> also seems to be inconsistent, and sometimes fixes itself with more document edits.

Notable change, unrelated to the original change queue fix, but potentially related - 
- #307 ExternalAnnotator replaces LocalInspectionTool for diagnostics
