### ISSUE TITLE
Duplicate diagnostics from LSPLocalInspectionTool and LSPCodeActionAnnotator

### ISSUE THREAD

**Issue by turkeylurkey** [OpenLiberty/liberty-tools-intellij#287]
After adding the code for LSP4MP 0.6.0 we see duplicate diagnostics (from LSPLocalInspectionTool and LSPCodeActionAnnotator) in the problems view. We need to revisit the design to merge the problem descriptors or not to create the duplicates in the first place.

**Comment by dshimo** [comment]
Resolved with PR #307
