### ISSUE TITLE
Document sync issue from new diagnostic style

### ISSUE THREAD

**Issue by turkeylurkey** [OpenLiberty/liberty-tools-intellij#288]
The merge with the LSP4MP 0.6.0 release caused diagnostic sync issues (from the diagnostics provided via <externalAnnotator> which uses the new LSPCodeActionAnnotator class, which has similar logic to the checkFile method currently have to force rerun to fix syncing)

The diagnostic that comes from LSPLocalInspectionTool is still fine from our fix. only the diagnostic from the externalAnnotator has sync issues

The symptom is that when you first fix the indicated code error the diagnostic is not removed but if you change the file again in any way the diagnostic is removed. Similarly, instead of changing the file a second time you can select a different application on the PC and when you return to IntelliJ the diagnostic will be removed.

**Comment by evie-lau** [comment]
From browsing other IntelliJ extensions that utilized ExternalAnnotators, at least a couple had done nothing in the `collectInformation` and `doAnnotate` methods, and put all the logic into the `apply` method.

This also seems to work for us, where `apply` runs late enough to be guaranteed the correct diagnostic information to be processed beforehand.
