### ISSUE TITLE
Libery tool window does not show the Start in container action for Gradle built application

### ISSUE THREAD

**Issue by mezarin** [OpenLiberty/liberty-tools-intellij#299]
The `Start in container` action does not show in the Liberty tool window for an application built using a liberty starter Gradle application, which defines the Liberty Gradle plugin like this:

```
plugins {
    id 'war'
    id 'io.openliberty.tools.gradle.Liberty' version '3.5.2'
}
```

<img width="1099" alt="image" src="https://user-images.githubusercontent.com/8353153/226909461-5feb9686-ce9f-46b6-b8a6-6334b9752afb.png">

**Comment by TrevCraw** [comment]
For gradle projects where the Liberty Gradle Plugin is defined as part of "buildscript -> dependencies", the `Start in container` option is available.

![image](https://user-images.githubusercontent.com/5885743/229201467-d51a0363-68a0-46b9-91ca-618f7019efae.png)

**Comment by TrevCraw** [comment]
This bug looks to be a result of not yet implementing a check for the LGP in the plugins block: https://github.com/OpenLiberty/liberty-tools-intellij/blob/7e21a25b82719f5794047e0eb709334c1d3f4ae2/src/main/java/io/openliberty/tools/intellij/util/LibertyGradleUtil.java#L108
