### ISSUE TITLE
Port RemoveModifierConflictQuickFix from LSP4Jakarta.

### ISSUE THREAD

**Issue by mrglavas** [OpenLiberty/liberty-tools-intellij#306]
Consume https://github.com/eclipse/lsp4jakarta/blob/main/jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/codeAction/proposal/quickfix/RemoveModifierConflictQuickFix.java, its dependencies and all of its child classes. Convert from the Eclipse APIs to Intellij's PSI: https://plugins.jetbrains.com/docs/intellij/psi.html.

Completion of this work should enable the following quick fixes:
- RemoveFinalModifierQuickFix
- RemoveStaticModifierQuickFix
- RemoveAbstractModifierQuickFix

related to #103

**Comment by turkeylurkey** [comment]
I just added RemoveInvalidInjectParamAnnotationQuickFix to the list in #103. It extends RemoveParamAnnotationQuickFix and RemoveModifierConflictQuickFix and it was left off the initial list by accident.

**Comment by mrglavas** [comment]
@turkeylurkey I just reviewed RemoveInvalidInjectParamAnnotationQuickFix. It's relationship with RemoveModifierConflictQuickFix looks like a hack. Modifiers are not annotations. Looks like what was done in the Eclipse version was for convenience to reuse the AST rewrite, but we're replacing that code completely. I think any relevant logic should be absorbed into RemoveParamAnnotationQuickFix, rather than it extending RemoveModifierConflictQuickFix.

**Comment by turkeylurkey** [comment]
Ok, you can redesign it. The diagnostic collectors translated well from the Eclipse project to the IntelliJ project but I've found the quick fixes do not. I'm just worried about future maintenance but it does not look like quick fix changes to the Eclipse project will be much use in the IntelliJ project.

**Comment by mrglavas** [comment]
Alright, I'll work on #314 next.
