### ISSUE TITLE
Port the Quick Fix class RemoveInvalidInjectParamAnnotationQuickFix

### ISSUE THREAD

**Issue by turkeylurkey** [OpenLiberty/liberty-tools-intellij#314]
Port the quick fix RemoveInvalidInjectParamAnnotationQuickFix and the class it extends, RemoveParamAnnotationQuickFix.

Depends on #306.

**Comment by mrglavas** [comment]
Pointer to LSP4Jakarta class: https://github.com/eclipse/lsp4jakarta/blob/main/jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/cdi/RemoveInvalidInjectParamAnnotationQuickFix.java
