### ISSUE TITLE
LSP4Jakarta Diagnostics do not appear on startup

### ISSUE THREAD

**Issue by turkeylurkey** [OpenLiberty/liberty-tools-intellij#329]
When you first start the IDE it takes a few seconds for all the language servers to start up. In this Jakarta sample we see no diagnostics.
![image](https://user-images.githubusercontent.com/24705144/230126443-2f396861-bbb4-407d-810e-37cb67914f5f.png)
But after we Hover over anything, the IDE is updated and the diagnostics are displayed.
![image](https://user-images.githubusercontent.com/24705144/230126749-3e7c2b79-57f0-4865-b827-13d2c93ea9fe.png)
The diagnostics should be displayed after the Jakarta language server starts and sends the publish diagnostics message.

**Comment by TrevCraw** [comment]
Seeing similar behaviour for the LCLS with server.env and bootstrap.properties.

For example, create a diagnostic in server.env
![image](https://user-images.githubusercontent.com/5885743/232157670-818d56c6-52c4-4609-b335-de0906d86e52.png)
Close, and reopen server.env - The diagnostic underline shows up right as the file is opened, but disappears immediately. You can see that there is still a red exclamation mark in the top corner of the file, but it does not show up in the "Problems" view.
![image](https://user-images.githubusercontent.com/5885743/232158012-e67ac17c-7627-46ad-8b0a-f56b59deb939.png)
The red exclamation mark eventually disappears as well.
![image](https://user-images.githubusercontent.com/5885743/232158157-816a3473-6e1a-45e8-8bbc-40ae097d4470.png)
Hovering does not trigger the diagnostic to show up
![image](https://user-images.githubusercontent.com/5885743/232158327-bce92a43-987e-4732-9db9-d5f0a4d6d95f.png)
Only input into the file (ie. type enter for new line) triggers the diagnostic to show up again
![image](https://user-images.githubusercontent.com/5885743/232158443-7d98b1bf-4658-4a89-926f-3e706ed0fb54.png)

**Comment by evie-lau** [comment]
Also similar behavior with Lemminx.

I noticed the `MicroProfileLanguageClient.java` has extra code that we don't have in any of the other language clients. In particular, the usage of a `MessageBusConnection` that subscribes to a topic for the MP project service. Wondering if this is responsible for some events triggered upon starting LSP4MP which gets the diagnostics published immediately upon startup.

**Comment by turkeylurkey** [comment]
Normally, after the language server starts, the first action is to send it a didOpen message when the IDE opens a file in the editor. Then the language server can send diagnostics on that file. This Message Bus may be the way the IDE communicates with the plugins.

**Comment by TrevCraw** [comment]
Still seeing the reported behaviour in bootstrap.properties and server.env. Doesn't seem like #355 resolved these issues.
New issue opened here to address the LCLS related issue: https://github.com/OpenLiberty/liberty-tools-intellij/issues/367
