### ISSUE TITLE
LSP4MP Completion: substitute correct class name in template

### ISSUE THREAD

**Issue by turkeylurkey** [OpenLiberty/liberty-tools-intellij#372]
When you use the completion item "mpliveness" a snippet of code is inserted but the name of the new class is not replaced properly in the template.
<img width="564" alt="image" src="https://user-images.githubusercontent.com/24705144/234702469-e0b7517d-eaad-4623-86ef-b8c70d13bacd.png">
In this image we see "${TM_FILENAME_BASE}" where we would expect the IDE to insert the correct class name.

**Comment by angelozerr** [comment]
It is because the LSP IJ client doesn't support completion snippet, I plan to work on that in https://github.com/redhat-developer/intellij-quarkus/issues/786

**Comment by angelozerr** [comment]
In the meantime lsp4jakarta should avoid returning snippet if ksp client cannot support it. It must check if client has the snippet capability. We did that in an all lour anguage server. I suggest that you see for instance our qute ls histed in quarkus ls
