### ISSUE TITLE
Add tests to cover refactored LSP4Jakarta JDT component

### ISSUE THREAD

**Issue by TrevCraw** [OpenLiberty/liberty-tools-intellij#379]
Either port over [JDT component tests](https://github.com/eclipse/lsp4jakarta/tree/main/jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/src/main/java/org/eclipse/lsp4jakarta/jdt) from the LSP4Jakarta repo or reuse UI based tests to cover all provided diagnostics and quick fixes.

**Comment by TrevCraw** [comment]
Decision was made to port LSP4Jakarta JDT component tests over to IntelliJ following a similar method to what intellij-quarkus did for the LSP4MP JDT component tests.

**Comment by mrglavas** [comment]
The initial integration of tests were delivered in: https://github.com/OpenLiberty/liberty-tools-intellij/pull/471.

Next steps:
- Enable all of the remaining diagnostic tests.
- Align the diagnostic tests with the message update synch from LSP4Jakarta.
- Synch with expanded test coverage being conributed to LSP4Jakarta.
- Enable the quick fix portion of the tests when quick fix support is restored.

**Comment by mrglavas** [comment]
Will close this issue after the PR enabling the rest of the diagnostics is delivered. Follow-up work is being tracked by #475 and #476.
