### ISSUE TITLE
Reexamine Diagnostics regarding properties file

### ISSUE THREAD

**Issue by turkeylurkey** [OpenLiberty/liberty-tools-intellij#392]
In issue https://github.com/OpenLiberty/liberty-tools-intellij/issues/328 we examine diagnostics created when one file has a dependency on another file. We change the second file and require the diagnostic on the first file to be updated even though it has not changed. 

Our solution is to create a list of listeners and to refresh the diagnostics on File A when we detect a change on File B.

We should investigate the Language Server Protocol specification to see if it provides support for this situation. If so we could take advantage of this support rather than implementing our own locally.

**Comment by angelozerr** [comment]
I have studied quickly the problem and now with my LSP console we can compare LSP traces between IJ and vscode.

In vscode when you save a microprofile-config.properties it report a notification  'microprofile/propertiesChanged' to notify to the MicroProfile LS that a config source file has been changed. The MicroProfile LS react to this notification by forcing the Java diagnostics for all opened Java files.

In other words, IJ should send this kind of notification when  microprofile-config.properties file is saved:

```
[Trace - 07:36:30 PM] Sending notification 'microprofile/propertiesChanged'.
{
  "jsonrpc": "2.0",
  "method": "microprofile/propertiesChanged",
  "params": {
    "type": [
      3
    ],
    "projectURIs": [
      "C:/Users/azerr/Downloads/demo/service-a/.idea/service-a.iml"
    ]
  }
}
```

I create a draft PR for this fix at https://github.com/redhat-developer/intellij-quarkus/pull/868

**Comment by anusreelakshmi934** [comment]
Tested with the latest lsp4ij feature branch (version - 0.0.2) .
When the microprofile-config.properties was changed, the diagnostic is updated in the java file. Also Sending notification 'microprofile/propertiesChanged' is visible in the LSP console.

https://github.com/user-attachments/assets/13b7ce60-721f-425a-b219-242d6b631c25

**Comment by turkeylurkey** [comment]
Thank you for checking this.
