### ISSUE TITLE
After diagnostic rewrite the diagnostics can still get out of sync

### ISSUE THREAD

**Issue by turkeylurkey** [OpenLiberty/liberty-tools-intellij#398]
Here is a test case with a diagnostic:
<img width="555" alt="image" src="https://github.com/OpenLiberty/liberty-tools-intellij/assets/24705144/1ed5a47b-f5a8-4c05-99b5-acbefc24141e">
I comment out the bad code:
<img width="555" alt="image" src="https://github.com/OpenLiberty/liberty-tools-intellij/assets/24705144/b3c1d098-01c2-4e45-873e-b885fe485da6">
I remove the comment characters and the diagnostic is not displayed:
<img width="568" alt="image" src="https://github.com/OpenLiberty/liberty-tools-intellij/assets/24705144/646b28e5-3b4f-4c41-a7d5-8ba7cc11e2c3">
A change of the file causes the diagnostic to be refreshed:
<img width="571" alt="image" src="https://github.com/OpenLiberty/liberty-tools-intellij/assets/24705144/5e6de470-c087-4c59-8017-62acbd74132b">
Typing another character causes the diagnostic to be displayed with an invalid range:
<img width="568" alt="image" src="https://github.com/OpenLiberty/liberty-tools-intellij/assets/24705144/25c45edc-3010-437c-bb8d-d09c26844d2e">

**Comment by turkeylurkey** [comment]
There are other impacts of the sync problem. For instance a red light bulb for an intention action may still be displayed after the error is fixed.
<img width="671" alt="image" src="https://github.com/OpenLiberty/liberty-tools-intellij/assets/24705144/dad4398c-6e4d-4a4f-958c-92aa84481df5">

**Comment by dshimo** [comment]
It seems the synchronization roots are deeper than what we addressed. It may be worth investigating the latest changes to Quarkus if the sync related bugs are fixed. Or maybe revisit after realizing our vision of splitting off the IntelliJ language server layer as its own project.

**Comment by evie-lau** [comment]
Seems the whole document gets out of sync.

In some testing, I added a comment, then applied a quickfix, and the comment got lost (assuming it applied the quickfix to an older version of the file)

Initial state:
<img width="455" alt="image" src="https://github.com/OpenLiberty/liberty-tools-intellij/assets/689163/1cd802e3-0708-4602-b2fa-0f7fee4c257f">
Add comment:
<img width="422" alt="image" src="https://github.com/OpenLiberty/liberty-tools-intellij/assets/689163/9554f63e-57ee-44dc-8c5d-cbeebd5a8217">
Applied quickfix on class to remove the Scope annotations:
<img width="666" alt="image" src="https://github.com/OpenLiberty/liberty-tools-intellij/assets/689163/0da614be-c1e2-40d5-a85f-1daa63190af7">

**Comment by evie-lau** [comment]
The sync issue seems to usually fix itself with more document edits (when not trying to intentionally break it).

With continued testing, I was able to make it revert 2 lines of comments. Not sure if this is caused by the doc being 2 steps behind, or if typing the two comment lines in quick successions counted as a single new version of the file.

**Comment by turkeylurkey** [comment]
If you make an error in Java and use an IntelliJ quick fix to repair the error the "intention" marker remains until you click elsewhere. This seems like a sync error in base IntelliJ support.
![image](https://github.com/OpenLiberty/liberty-tools-intellij/assets/24705144/143e85d0-1300-44ee-9d0b-fc6c0147e9ad)
In this case I changed the class name by adding one letter. One of the quick fixes was to rename the class to a valid name (matching the file name). After executing the quick fix the red light bulb marker was left behind.

**Comment by angelozerr** [comment]
Please read my comment at https://github.com/OpenLiberty/liberty-tools-intellij/issues/434#issuecomment-1581998896

**Comment by turkeylurkey** [comment]
The invalid intention marker also appears in server.xml:
![image](https://github.com/OpenLiberty/liberty-tools-intellij/assets/24705144/4bb1cde4-f06a-4b1c-803d-a759fcae00d5)

**Comment by turkeylurkey** [comment]
I can no longer reproduce the diagnostic sync problem in this way and we haven't seen it in other situations either. However the red light bulb problem seems the same as before and it definitely has different symptoms than the diagnostic sync (e.g. with the diagnostic sync problem typing space would move the red underline to an invalid place).

**Comment by turkeylurkey** [comment]
@anusreelakshmi934 Please check this off the list.
