### ISSUE TITLE
(LSP4Jakarta 379) Code snippets are offered in invalid contexts

### ISSUE THREAD

**Issue by Jonathan-Maciel** [OpenLiberty/liberty-tools-intellij#401]
Slack Thread: https://ibm-cloud.slack.com/archives/CJ6U2DWPJ/p1683748682669629

The code snippet options are being prepended to the autocomplete list.
![03ab44a5-6351-4e3e-a19e-02a6b034834e](https://github.com/OpenLiberty/liberty-tools-intellij/assets/104153033/c6c8ef5d-20e7-4cd0-878a-88046e6fc4f0)

This can be seen in different contexts.
![44191768-bbd9-44e8-ae05-245699cebb59](https://github.com/OpenLiberty/liberty-tools-intellij/assets/104153033/8c6b18da-eb5a-4118-b0fe-fc9f480a5fd7)

Possible quick fixes are:
- only offer code snippets when typing into a blank line 
- append to the suggested list to be below the valid options

**Comment by TrevCraw** [comment]
This is due to LSP4Jakarta snippets not being context aware. Issue for that here: https://github.com/eclipse/lsp4jakarta/issues/379

**Comment by angelozerr** [comment]
Please note that MicroProfile LS manages completion context aware very good.

At first snippet completion appears only if there are à given Java type in the classpath.

The ladt version of MicroProfile LS is smarter and check vhere completion is triggered like before a method déclaration. It means that when you open completion inside à method body the annotation snippet will not shown.

Those two features are managed by the external component like we did with JDT. We need to implement that iñ IJ.

I suggest that Jakarta LS follows the same strategy than MicroProfile LS

**Comment by rumanaHaque** [comment]
Using the latest VSCode driver that @TrevCraw uploaded on May 25th, validated that this problem does not occur any more.

Here's a screenshot of auto-complete for `import jakarta.`

<img width="782" alt="image" src="https://github.com/OpenLiberty/liberty-tools-intellij/assets/31224827/5392c2e1-6609-42db-8819-51a7f88c0c81">

**Comment by turkeylurkey** [comment]
Methods this feature uses:
- getJavaCursorContextKind
- offsetOfFirstNonAnnotationModifier
- FindWhatsBeingAnnotatedASTVisitor
- getJavaCursorPrefix

**Comment by turkeylurkey** [comment]
Investigating how the Eclipse code is working and converting to Psi format.

**Comment by angelozerr** [comment]
> Investigating how the Eclipse code is working and converting to Psi format.

@fbricon is working on java cursor context for IJ for LSP4MP https://github.com/redhat-developer/intellij-quarkus/pull/895 I suggest that you follow this PR.

**Comment by cherylking** [comment]
Please post progress in this issue daily. Is someone working on the `FindWhatsBeingAnnotatedASTVisitor` method?

**Comment by turkeylurkey** [comment]
We decided to use the code Angelo pointed out. It returned the correct values for snippet context. Unfortunately the snippets still appear in strange contexts on IntelliJ. We've added a question to the RedHat Slack channel for assistance.

**Comment by TrevCraw** [comment]
Defined expectations for snippet context behaviour in this box note: https://ibm.ent.box.com/notes/1227832954133
Working through recording the current behaviour in each IDE (Including the latest updates from intellij-quarkus in LT IntelliJ).

**Comment by TrevCraw** [comment]
New snippet behaviour with Jakarta fix for "before class" context: https://ibm.ent.box.com/notes/1229927917191

**Comment by TrevCraw** [comment]
This issue was resolved by updates in LSP4Jakarta + https://github.com/OpenLiberty/liberty-tools-intellij/pull/433

Issue open to track any other snippet behaviour updates: https://github.com/OpenLiberty/liberty-tools-intellij/issues/481
