### ISSUE TITLE
Quick fixes do not appear after all files are closed and a file is reopened

### ISSUE THREAD

**Issue by turkeylurkey** [OpenLiberty/liberty-tools-intellij#412]
Start with a Java file with a diagnostic with a quick fix. Then close the file and all other Java files and reopen the Java file. Hover over the diagnostic and observe the quick fix is no longer available. 
![image](https://github.com/OpenLiberty/liberty-tools-intellij/assets/24705144/f72a8c52-27f4-41e4-af65-7df0c87534fb)

**Comment by turkeylurkey** [comment]
If you open another file it also does not have quick fixes.
![image](https://github.com/OpenLiberty/liberty-tools-intellij/assets/24705144/a0510507-46e1-4a14-8f7b-be5eaac7460d)

**Comment by angelozerr** [comment]
Have you the same problem with quickfixes cominf from lsp4mp. If yes could you try IJ Quarkus. I have never seen this kind of problem since I improved diagnostics and code actions

**Comment by turkeylurkey** [comment]
It took three tries but on the third try I can reproduce this with a MicroProfile quick fix:
![image](https://github.com/OpenLiberty/liberty-tools-intellij/assets/24705144/88301580-144d-418b-8b4a-07998d176b9a)

**Comment by angelozerr** [comment]
If you wait few seconds and you try to open the quickfix , is it  working?

**Comment by turkeylurkey** [comment]
No, once it gets into no-quickfix mode there are no quick fixes. Even if you open another file. The IDE does not send the codeAction message to the language server. Perhaps the IDE does not call our plugin but I have not investigated further.

**Comment by angelozerr** [comment]
I cannot reproduce in IJ Quarkus. I suggest that you integrate my LSP console to trace LSP requests/responses and understand more your problem

![image](https://github.com/OpenLiberty/liberty-tools-intellij/assets/1932211/7728ea68-7556-4702-9187-85b81e42c93e)

**Comment by anusreelakshmi934** [comment]
Using Latest Lsp4ij (0.0.2) I am no longer able to reproduce the error. opened a java file with a diagnostic with a quick fix. Then closed the file and all other Java files and reopen the Java file. Hover over the diagnostic and observe the quick fix is available.

**Comment by turkeylurkey** [comment]
I tried many times on 6 different files but I was not able to reproduce this. I also tried to restart the Jakarta and the MP language servers and open/reopen files but the quick fixes appeared.
