### ISSUE TITLE
Icons and wording should be action specific

### ISSUE THREAD

**Issue by kathrynkodama** [OpenLiberty/liberty-tools-intellij#42]
Run action icon and wording should be more dev mode specific.

Icons for Liberty actions should be specific to action, ie. stop icon for stop action, html icon for viewing integration report, etc.

![image](https://user-images.githubusercontent.com/26146482/110815980-ee333b80-8258-11eb-9699-f681e1155695.png)

See full list of IntelliJ icons here: https://jetbrains.design/intellij/resources/icons_list/

**Comment by kathrynkodama** [comment]
Action names should include "Liberty" or "dev mode" so that when actions are discovered via the IntelliJ Actions list, users understand what they do (outside of the context of the dashboard)

**Comment by kathrynkodama** [comment]
Wording via the Actions list has already been updated to included "Liberty"

**Comment by kathrynkodama** [comment]
Noting that there are two ways for these Liberty actions to be exposed. 

1. Through the Liberty dashboard view:
<img width="469" alt="image" src="https://user-images.githubusercontent.com/26146482/189160204-05657319-0e40-4c8e-bbb0-32bcc34f2a57.png">

2. Through the IntelliJ actions list:
<img width="678" alt="image" src="https://user-images.githubusercontent.com/26146482/189160269-340fc24b-6a9e-496e-81e4-3c7e53c5ceb9.png">

A few questions:
1. What should the icons be for each of the actions under the dashboard view (currently the gear)
2. What makes the most sense for the wording via the dashboard and actions list? Should they be consistent across both?  This would apply across all IDEs (not just IntelliJ).

Some options:
- Start
- Start dev mode
- Start Liberty dev mode
- Liberty: Start dev mode

**Comment by kathrynkodama** [comment]
Team decision was to use the same icons & wording as Liberty Tools for VS Code, see https://github.com/OpenLiberty/liberty-tools-vscode/blob/main/package.nls.json

**Comment by TrevCraw** [comment]
Enhancement issue for updating the gear icons: https://github.com/OpenLiberty/liberty-tools-intellij/issues/200
