### ISSUE TITLE
Windows: Completion choices for properties in bootstrap.properties includes Java packages.

### ISSUE THREAD

**Issue by mrglavas** [OpenLiberty/liberty-tools-intellij#430]
I saw this with a recent `liberty-tools-intellij-0.0.9-SNAPSHOT.zip`

![image](https://github.com/OpenLiberty/liberty-tools-intellij/assets/890521/17a32956-c8ee-421c-81cf-9328e3063d0a)

I don't remember seeing these in the list when I last tested this six months ago. These options don't seem to belong here.

I'm also seeing these options offered in server.env:

![image](https://github.com/OpenLiberty/liberty-tools-intellij/assets/890521/29f2cb57-34fd-4a5a-9c80-a5f82b4af2ec)

**Comment by TrevCraw** [comment]
Duplicate of https://github.com/OpenLiberty/liberty-tools-intellij/issues/343
