### ISSUE TITLE
MicroProfile snippets are not context aware

### ISSUE THREAD

**Issue by TrevCraw** [OpenLiberty/liberty-tools-intellij#431]
The ideal solution is to upgrade LSP4MP from version 0.6.0 to 0.7.0, however, this is not targeted for the GA release

Investigate a way to disable MP snippets only through the code

Test removing the snippet JSON files from the LSP4MP jar

**Comment by TrevCraw** [comment]
Initial investigation by @evie-lau and @turkeylurkey into disabling MP snippets by code shows that this may not be a feasible solution.

Initial testing with an LSP4MP jar without the snippet JSON files looks promising.

**Comment by turkeylurkey** [comment]
Using LSP4MP v0.10.0 now in latest lsp4ij branch. Can probably close this.
