### ISSUE TITLE
Jakarta Quickfixes are out of sync, and can revert document when applied

### ISSUE THREAD

**Issue by evie-lau** [OpenLiberty/liberty-tools-intellij#434]
Initially commented in #398 and #425 thinking they were different issues, but from further testing, Jakarta quickfixes seem to be the root cause - starting after PR #376 was merged.

Note: seems 376 did indeed fix what it was meant to do regarding starting LS on plugin startup. And MP/LCLS quickfixes works fine without any sync issues. From discussion, the Jakarta sync issues possibly come from the way it is implemented differently from MP.

_**This can delete user code/comments, potentially delete multiple lines or entire methods.**_

Restating some symptoms:

### Jakarta Quickfix after adding text
If applying Jakarta quickfix immediately after adding text (comments, code) in the file, the newly added text can get lost as the quickfix is applied to a previous version of the document and replaces the existing document. 
Sample reproduction:
Initial state:
<img width="455" alt="image" src="https://github.com/OpenLiberty/liberty-tools-intellij/assets/689163/1cd802e3-0708-4602-b2fa-0f7fee4c257f">
Add comment:
<img width="422" alt="image" src="https://github.com/OpenLiberty/liberty-tools-intellij/assets/689163/9554f63e-57ee-44dc-8c5d-cbeebd5a8217">
Applied quickfix on class to remove the Scope annotations:
<img width="666" alt="image" src="https://github.com/OpenLiberty/liberty-tools-intellij/assets/689163/0da614be-c1e2-40d5-a85f-1daa63190af7">

### Jakarta Quickfix after deleting lines
If applying Jakarta quickfix immediately after deleting line(s) in the file, 
```
java.lang.IndexOutOfBoundsException: Wrong line: 27. Available lines count: 27
	at com.intellij.openapi.editor.impl.LineSet.checkLineIndex(LineSet.java:200)
	at com.intellij.openapi.editor.impl.LineSet.getLineStart(LineSet.java:181)
	at com.intellij.openapi.editor.impl.DocumentImpl.getLineStartOffset(DocumentImpl.java:1027)
	at io.openliberty.tools.intellij.lsp4mp.lsp4ij.LSPIJUtils.toOffset(LSPIJUtils.java:118)
	at io.openliberty.tools.intellij.lsp4mp.lsp4ij.LSPIJUtils.applyWorkspaceEdit(LSPIJUtils.java:223)
	at io.openliberty.tools.intellij.lsp4mp.lsp4ij.LSPIJUtils.applyWorkspaceEdit(LSPIJUtils.java:208)
	at io.openliberty.tools.intellij.lsp4mp.lsp4ij.operations.codeactions.LSPCodeActionIntentionAction.apply(LSPCodeActionIntentionAction.java:111)
	at io.openliberty.tools.intellij.lsp4mp.lsp4ij.operations.codeactions.LSPCodeActionIntentionAction.invoke(LSPCodeActionIntentionAction.java:99)
...
```

**Comment by turkeylurkey** [comment]
The language server asks the IDE for the code actions so IntelliJ can return an empty list if needed to completely disable all lsp4jakarta quick fixes.

**Comment by angelozerr** [comment]
IMHO I think you would integrate the LSP console that I have implemented for IJ Quarkus. As it is very hard to debug this usecase, LSP console will show you the request, response of codeAction:

![image](https://github.com/OpenLiberty/liberty-tools-intellij/assets/1932211/f5f795d1-75c8-468d-8a8a-6099ff84cb4b)

I suspect the problemis because lsp4jakarta doesn't support resolve code action (I have not seen your code) and code action process takes some times (but perhaps I'm wrong). There is perhapsa bug with my code actions refresh. 

With LSP console you will see easily code actions which are requested, the response and if it is resolved or not.

**Comment by turkeylurkey** [comment]
@angelozerr perhaps you could propose a fix such that if a language server does not support resolve code action then the IntelliJ IDE will fetch code actions every time we publish diagnostics. Note well that we may also have a bug where lsp4jakarta does not report properly whether it supports resolve code action, we'd need to check.

**Comment by angelozerr** [comment]
> @angelozerr perhaps you could propose a fix such that if a language server does not support resolve code action then the IntelliJ IDE will fetch code actions every time we publish diagnostics. Note well that we may also have a bug where lsp4jakarta does not report properly whether it supports resolve code action, we'd need to check.

Ok thanks for your feedback. So I think it is a performance problem. I will try to reproduce your problem with our MP code action by disabling resolve and if I see some problem I will try to fix it.

**Comment by turkeylurkey** [comment]
Thank you. All the lsp4jakarta code actions are of the sort "remove annotation from field" or similar so they are not slow. I'm not aware of testing on large Java files with many errors so I'm not sure of the performance when stressed.

**Comment by angelozerr** [comment]
I wonder if your problem with out of sync comes from your hack https://github.com/OpenLiberty/liberty-tools-intellij/blob/af8fd48ad3e9f8881b712eab0a9002132e391952/src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/DocumentContentSynchronizer.java#L120

You break the LSP concept and validation trigger must be done by MicroProfile LS and not by IJ himself by forcing again validation.

Could you re-enable code action and remove your hack to see if it works better.

I will work soon on this problem of refresh validation. I have already fixed a problem with the uri which was wrong when propertyChanged events are fired but sometimes it doesn't work. I need to investigate the problem.

**Comment by angelozerr** [comment]
Have you the same issue with Mp ls?

If no it means that there is à problem with Jakarta LS or IJ.

If yes it means that it is a problem with your lsp4ij and I suspect your Hack with documentFullRefresh could be the root cause of your all out of sync problem. Perhaps Im wrong but It think it could be intersting  for you to enable again code action and remove the documentFullRefresh code just to see if your code action are working without documentFullRefresh

**Comment by turkeylurkey** [comment]
I have not seen a problem with the MP quick fixes but I suspect it is because they use the resolve mechanism to update the fix before applying it. I haven't researched this. Jakarta just creates a simple resolved fix up front.

**Comment by angelozerr** [comment]
I redo the code actions mechanism which should improve performance, see https://github.com/redhat-developer/intellij-quarkus/pull/1042

**Comment by turkeylurkey** [comment]
I tried `ScopeDeclaration` and also `MethodConstraintValidation` and the quick fixes did not delete the added text. 
Thank you @anusreelakshmi934
