### ISSUE TITLE
incompatibility with latest intellij ?

### ISSUE THREAD

**Issue by ljgp** [OpenLiberty/liberty-tools-intellij#487]
I updated Intellij this morning and now get this when trying to install the plugin:

Plugin 'Liberty Tools' (version '23.0.6') is not compatible with the current version of the IDE, because it requires build 231.* or older but the current build is IU-232.9559.62

**Comment by TrevCraw** [comment]
@ljgp Thank you for raising this issue. It is correct that Liberty Tools for IntelliJ version `23.0.6` is only compatible with IntelliJ versions `2023.1.*`. We will look into addressing this issue as a priority for the next release.

**Comment by TrevCraw** [comment]
Update compatibility limit here: https://github.com/OpenLiberty/liberty-tools-intellij/blob/main/src/main/resources/META-INF/plugin.xml#L21

Perform manual and automated tests to confirm Liberty Tools is behaving correctly with latest IntelliJ IDEA version

**Comment by tommyNy** [comment]
The same in case Idea IU-232

Plugin 'Liberty Tools' (version '23.0.6') is not compatible with the current version of the IDE, because it requires build 231.* or older but the current build is IU-232.9559.62
