### ISSUE TITLE
Update demo video

### ISSUE THREAD

**Issue by TrevCraw** [OpenLiberty/liberty-tools-intellij#507]
YouTube video link: https://www.youtube.com/watch?v=2T-ALsTGRY0

Updates required:
- intro screen has early release
- intro audio mentions “early release”
- outro screen shot shows early release on marketplace
- outro audio mentions “early release”
- only shows completion/snippets for editing assistance
  - hover, diagnostic and quick fix all need to be added
  - consider releasing a separate "update" video for the extra editing assistance features

**Comment by TrevCraw** [comment]
@aparnamichael First step is to come up with new demo steps and script for the video.

**Comment by aparnamichael** [comment]
Completed the demo video and addressed all the review comments.
https://ibm.box.com/s/stxg7klpoeuek63h0j1y5su8q9b3h3wo

**Comment by TrevCraw** [comment]
New demo video available on the Open Liberty YouTube page: https://youtu.be/O-dN3yHSPdQ
