### ISSUE TITLE
Run IntelliJ plugin verifier against latest code

### ISSUE THREAD

**Issue by TrevCraw** [OpenLiberty/liberty-tools-intellij#509]
https://plugins.jetbrains.com/docs/intellij/verifying-plugin-compatibility.html

Manually run the IntelliJ plugin verifier tool against the latest code. Investigate any compatibility issues and determine steps for resolution, which may require contacting JetBrains.

**Comment by cherylking** [comment]
@TrevCraw I know you updated in our SoS about this, but can you add updates here in the issue on where this stands....what progress and what issues there are? I know this held us up a bit last release at the end. TIA

**Comment by TrevCraw** [comment]
Ran into issues with trying to run the local plugin verifier. It was reporting many more compatibility issues than the plugin verifier in the marketplace. Reached out to JetBrains and they have opened an issue to address the problem: https://youtrack.jetbrains.com/issue/MP-6067

**Comment by TrevCraw** [comment]
The latest run with the local plugin verifier reported these two issues:
```
Compatibility problems

Invocation of unresolved method java.util.stream.Stream.toList() : List details
(Invocation of unresolved method java.util.stream.Stream.toList() : List, Method io.openliberty.tools.intellij.liberty.lsp.LibertyCustomConfigListener.after(java.util.List events) : void contains an *invokeinterface* instruction referencing an unresolved method java.util.stream.Stream.toList() : java.util.List. This can lead to **NoSuchMethodError** exception at runtime.) (Invocation of unresolved method java.util.stream.Stream.toList() : List, Method io.openliberty.tools.intellij.liberty.lsp.LibertyConfigLanguageClient.processConfigXml(java.util.List uris) : void contains an *invokeinterface* instruction referencing an unresolved method java.util.stream.Stream.toList() : java.util.List. This can lead to **NoSuchMethodError** exception at runtime.)

Package 'org.eclipse.xtext' is not found
(Package 'org.eclipse.xtext' is not found, Package 'org.eclipse.xtext' is not found along with its class org.eclipse.xtext.xbase.lib.util.ToStringBuilder. Probably the package 'org.eclipse.xtext' belongs to a library or dependency that is not resolved by the checker. It is also possible, however, that this package was actually removed from a dependency causing the detected problems. Access to unresolved classes at runtime may lead to **NoSuchClassError**. The following classes of 'org.eclipse.xtext' are not resolved: Class org.eclipse.xtext.xbase.lib.util.ToStringBuilder is referenced in org.eclipse.lsp4mp.ls.commons.client.CommandCapabilities.toString() : String org.eclipse.lsp4mp.ls.commons.client.CommandKindCapabilities.toString() : String )
```

**Comment by cherylking** [comment]
The `org.eclipse.xtext` package comes from a dependency used by the `org.eclipse.lsp4j` dependency which is used by Eclipse LemMinX.

```
[INFO] +- org.eclipse.lemminx:org.eclipse.lemminx:jar:0.26.1:provided
[INFO] |  +- com.google.guava:guava:jar:32.0.1-jre:provided
[INFO] |  |  +- com.google.guava:failureaccess:jar:1.0.1:provided
[INFO] |  |  \- com.google.code.findbugs:jsr305:jar:3.0.2:provided
[INFO] |  +- com.google.code.gson:gson:jar:2.10.1:provided
[INFO] |  +- org.eclipse.lsp4j:org.eclipse.lsp4j:jar:0.20.1:provided
[INFO] |  |  \- org.eclipse.lsp4j:org.eclipse.lsp4j.generator:jar:0.20.1:provided
[INFO] |  |     \- org.eclipse.xtend:org.eclipse.xtend.lib:jar:2.28.0:provided
[INFO] |  |        +- org.eclipse.xtext:org.eclipse.xtext.xbase.lib:jar:2.28.0:provided
```

**Comment by TrevCraw** [comment]
On advice from the JetBrains team, we set up a new repo on the JetBrains Marketplace and uploaded our latest snapshot there. This triggered the marketplace plugin verifier to run, which did not report any compatibility issues. For those who have access, the report can be found here: https://plugins.jetbrains.com/plugin/14856-liberty-tools/edit/versions/prerelease

**Comment by TrevCraw** [comment]
Closing, since the main goal of this issue was to find out any compatibility issues before publishing. We achieved that through uploading our driver to a "prerelease" channel and seeing the verifier results directly in the JetBrains marketplace. This is the process we should continue to follow for future releases.
