### ISSUE TITLE
Custom config dir/files support does not initialize on IDE startup or opening project

### ISSUE THREAD

**Issue by evie-lau** [OpenLiberty/liberty-tools-intellij#535]
### Problem
Support for [custom config dir/files](https://github.com/OpenLiberty/liberty-language-server/issues/66#issuecomment-1766991570) doesn't work on **IDE startup** or **opening a new project**
Currently it only triggers when running `mvn liberty:create` or `gradle libertyCreate`, or if the `liberty-plugin-config.xml` file gets modified after opening the project in the IDE.

### Cause
This is because our current version of lsp4ij does not support initializing LSP workspaces. [`intellij-quarkus`](https://github.com/redhat-developer/intellij-quarkus) has already added this support in a newer version of lsp4ij.

### Solution
Either
- Bring our version of lsp4ij up to date with `intellij-quarkus` to support workspaces.
- Wait for the common lsp4ij component and switch over to that.

**Note**: these should also remove the need for the filewatcher introduced in #510, as there will be support for LSP's `workspace/didChangeWatchedFiles`

**Comment by turkeylurkey** [comment]
The first init msg has 
```
"workspaceFolders": [
    {
      "uri": "file:///Users/turk/demo/guide-getting-started/",
      "name": "guide-getting-started"
    }
```

**Comment by turkeylurkey** [comment]
Fixed by using the latest lsp4ij as tracked by #592.
