### ISSUE TITLE
Create 23.0.12 release notes and update documentation

### ISSUE THREAD

**Issue by TrevCraw** [OpenLiberty/liberty-tools-intellij#565]
- Create 23.0.12 release notes
- Identify any new areas or areas that require update for documentation
- Add/update documentation as needed
---
- [x] Update [user guide](https://github.com/OpenLiberty/liberty-tools-intellij/blob/main/docs/user-guide.md) to document Jakarta diagnostic and quick fixes
- [x] Maybe update [user guide](https://github.com/OpenLiberty/liberty-tools-intellij/blob/main/docs/user-guide.md) to split the MP & Jakarta dev section into separate sections?
- [x] Update the screen shots in the [custom config start section](https://github.com/OpenLiberty/liberty-tools-intellij/blob/main/docs/user-guide.md#start-your-application-in-dev-mode-with-configuration) of the user guide to show the run/debug config with the "run in container" option. Add a sentence to explain that checking that check box will start dev mode in container mode.

**Comment by turkeylurkey** [comment]
As we discussed I kept the MP and Jakarta section intact.
