### ISSUE TITLE
FVT: Opening a parent folder with two gradle projects not trigger the "Start action."

### ISSUE THREAD

**Issue by vaisakhkannan** [OpenLiberty/liberty-tools-intellij#568]
In Linux, when you try to open a parent folder containing two gradle projects, the "Start action" is not triggered.

I tried Using the below Configurations
OS : RedHat Linux
Version : 9.2
Intellij Version: 2023.2.4

<img width="1396" alt="Screenshot 2023-11-07 at 10 13 10 PM" src="https://github.com/OpenLiberty/liberty-tools-intellij/assets/133869023/dd638b8e-8121-419a-84ed-02b3ee64aa39">

<img width="473" alt="Screenshot 2023-11-07 at 2 59 23 PM" src="https://github.com/OpenLiberty/liberty-tools-intellij/assets/133869023/b7454d15-a882-4e71-a04d-d2c24c080374">

This issue is related to #563 , which specifies Maven project. However, in this case, it's  Gradle project.

 I've tried it using both Wrapper and Local Installation in the Gradle Distribution of Build Tool. I am encountering the same popup message in both cases when trying to start the server.

**Comment by turkeylurkey** [comment]
Do you know how to get IntelliJ to load a gradle file so it appears in the gradle tool window and the gradle settings?

**Comment by vaisakhkannan** [comment]
When I opened the parent folder for the first time, I received the pop-up message below and clicked the 'Load' button. If we don't do this, we won't get Gradle settings—that's my understanding.

<img width="456" alt="Screenshot 2023-11-09 at 11 16 42 AM" src="https://github.com/OpenLiberty/liberty-tools-intellij/assets/133869023/2d301c85-853e-4edf-b23b-718b4b70351a">

I am uploading the video of reproducing the issue


https://github.com/OpenLiberty/liberty-tools-intellij/assets/133869023/750f9f07-7f3b-4f87-a59c-b8e033c07d57

**Comment by turkeylurkey** [comment]
The answer to my question above. The messages inside IntelliJ were a bit more helpful. You can unlink a project you "loaded" in the way shown above in the Gradle Tool window (dashboard). You can load a gradle project on demand by right clicking on `build.gradle` and selecting `Link Gradle project`
<img width="465" alt="image" src="https://github.com/OpenLiberty/liberty-tools-intellij/assets/24705144/53715b4c-47d4-4e75-9714-6cf21d7bbb22">
