### ISSUE TITLE
An exception (java.lang.IndexOutOfBoundsException) occurred during quick fix testing

### ISSUE THREAD

**Issue by vaisakhkannan** [OpenLiberty/liberty-tools-intellij#588]
I noticed the following exception while testing the Java file present in the Jakarta-sample.
One thing I found is that the exception occurs when we perform code actions on two different diagnostics in the same Java file.

![Screenshot 2023-11-27 at 10 32 26 AM](https://github.com/OpenLiberty/liberty-tools-intellij/assets/133869023/dfc97505-6696-4c69-9f25-4720c7981899)

NOTE : **We believe moving up to the latest LSP4Jakarta will resolve the issue**

**Comment by anusreelakshmi934** [comment]
Testes using the latest lsp4ij version (0.0.2) was not able to reproduce this error.

**Comment by TrevCraw** [comment]
@vaisakhkannan Can you confirm that you are no longer seeing this bug when using the `lsp4ij-market-0.0.2-integration` feature branch?

**Comment by vaisakhkannan** [comment]
@anusreelakshmi934 , @TrevCraw I tested with `lsp4ij-market-0.0.2-integration` feature branch , its working fine as expected and was not able to reproduce the exception that mentioned in this issue
