### ISSUE TITLE
Transform the Quick fixes related to RemoveAnnotationConflictQuickFix to implement the code action participant extension point

### ISSUE THREAD

**Issue by vaisakhkannan** [OpenLiberty/liberty-tools-intellij#593]
See the initial work completed here: https://github.com/OpenLiberty/liberty-tools-intellij/issues/310.

In addition to refactoring the code, the code action participants will need to be added to the plugin.xml and the relevant Jakarta EE code action tests should be enabled.

After enabling RemoveAnnotationConflictQuickFix also implement:
- [x] RemoveAnnotationConflictQuickFix
- [x] RemoveMultipleAnnotations
- [x] JsonbTransientAnnotationQuickFix
- [x] ScopeDeclarationQuickFix

Other quick fixes which extend RemoveAnnotationConflictQuickFix. Enable and test:
- [ ] ConflictInjectMultipleConstructorQuickFix?
- [x] ConflictProducesInjectQuickFix
- [x] DeleteConflictMapKeyQuickFix
- [x] JsonbAnnotationQuickFix
- [x] RemoveInjectAnnotationQuickFix
- [x] RemovePostConstructAnnotationQuickFix
- [x] RemovePreDestroyAnnotationQuickFix
- [x] RemoveProduceAnnotationQuickFix

**Comment by vaisakhkannan** [comment]
Issue found:

In the DeleteConflictMapKeyQuickFix() constructor, there is a direct passing of 2 annotations.

<img width="1109" alt="Screenshot 2024-01-11 at 7 23 34 PM" src="https://github.com/OpenLiberty/liberty-tools-intellij/assets/133869023/e64381be-f0c6-4d40-910c-92f46d5c61ff">

In the parent class RemoveAnnotationConflictQuickFix, the above two annotations are consistently obtained, as depicted in the image.
<img width="651" alt="Screenshot 2024-01-11 at 7 23 12 PM" src="https://github.com/OpenLiberty/liberty-tools-intellij/assets/133869023/98c7484b-dcb7-4321-9187-322a13075601">

This is causing an issue with resolvecodeaction. I can't able to perform one codeAction at a time for the quick fix **DeleteConflictMapKeyQuickFix** class.

All quick fixes are functioning correctly, except for ScopeDeclarationQuickFix.

**Comment by mrglavas** [comment]
@vaisakhkannan You said: "This is causing an issue with resolvecodeaction. I can't able to perform one codeAction at a time for the quick fix DeleteConflictMapKeyQuickFix class." Can you explain why?

**Comment by vaisakhkannan** [comment]
@mrglavas I resolved the above issue by comparing the current **annotation** from the _annotationslist_ with the passed annotation using **extendedData**. If necessary, I will provide further explanation during today's discussion.

**Comment by mrglavas** [comment]
@vaisakhkannan Correct, you need to store any additional context required to resolve the code action in the `extendedData` map. I suspected that's what you were likely missing from your solution but wanted more clarification.

**Comment by vaisakhkannan** [comment]
With #725, Enabled one more quickfix class `ConflictProducesInjectQuickFix` and `ConflictInjectMultipleConstructorQuickFix` has been removed from the lsp4kjakarta repository with this **PR** https://github.com/eclipse/lsp4jakarta/pull/495. Instead of **`ConflictInjectMultipleConstructorQuickFix`**, they are now using **`RemoveInjectAnnotationQuickFix`**. So I removed the **ConflictInjectMultipleConstructorQuickFix** class from our repo and aligned the implementation with `LSP4Jakarta`.
