### ISSUE TITLE
Latest IntelliJ plugin not compatible with latest IntelliJ

### ISSUE THREAD

**Issue by ljgp** [OpenLiberty/liberty-tools-intellij#602]
In the latest IntelliJ I get:
Plugin 'Liberty Tools' (version '23.0.12') is not compatible with the current version of the IDE, because it requires build 232.* or older but the current build is IU-233.11799.241

**Comment by TrevCraw** [comment]
@ljgp thank you for opening an issue. We are currently working on support for IntelliJ IDEA 2023.3.x. The issue for that is here: https://github.com/OpenLiberty/liberty-tools-intellij/issues/590

**Comment by TrevCraw** [comment]
Closing as duplicate of #590
