### ISSUE TITLE
Found LSP4Jakarta ambiguously matches the expected class names when checking diagnostics, applying quick fixes, etc ...

### ISSUE THREAD

**Issue by vaisakhkannan** [OpenLiberty/liberty-tools-intellij#611]
Found LSP4Jakarta unambiguous matches, the expected class names when checking diagnostics, applying quick fixes, etc... (e.g. @jakarta.ws.rs.PUT vs @my.random.pkg.PUT).

![Screenshot 2024-01-01 at 2 05 03 PM (1)](https://github.com/OpenLiberty/liberty-tools-intellij/assets/133869023/d5074d56-d68e-496b-9777-81a6d3937396)

In this image, we observe repeated annotations, with one is from "Jakarta." and another from "Javax.". As a temporary solution, we filtered out names starting with "Jakarta."

![Screenshot 2024-01-09 at 6 26 59 PM](https://github.com/OpenLiberty/liberty-tools-intellij/assets/133869023/dd16a72c-fd27-4cec-915e-403fa9cc9877)

In this image, there are still unambiguous matches even though we filtered out names that begin with "Jakarta."

Mentioning this issue that opened in lsp4jakarta --> https://github.com/eclipse/lsp4jakarta/issues/507

**Comment by mrglavas** [comment]
I recommend that this issue be addressed by updating all of the diagnostic collectors to include fully qualified class names in the diagnostic data that they produce. Search for usage of `io.openliberty.tools.intellij.lsp4jakarta.lsp4ij.AbstractDiagnosticsCollector.getSimpleName()`. We should not be calling this method when producing the diagnostic data and should ensure that only qualified names are reported. All quick fixes that consume class names from a diagnostic should be reviewed and updated (if necessary) to correctly consume qualified names. For messages or labels that will be displayed to the user it is generally fine to continue using the simple name, but that should be computed as late as possible to avoid issues with matching class names in the diagnostic collectors and quick fixes.

**Comment by aparnamichael** [comment]
io.openliberty.tools.intellij.lsp4jakarta.lsp4ij.AbstractDiagnosticsCollector class have 14 child classes, among 14 child classes 2 of the following child classes were using getSimpleName() method when producing the diagnostic data.

1. ManagedBeanDiagnosticsCollector.java
2. JsonbDiagnosticsCollector.java

I have updated the above diagnostic collector classes to include fully qualified class names in the diagnostic data. And fixed the quick fix  issue of JsonbTransientAnnotationQuickFix and ScopeDeclarationQuickFix.

**Comment by aparnamichael** [comment]
I have gone through all of the diagnostic classes and all of them are child class of AbstractDiagnosticsCollector. And all of these classes are using fully qualified name.

**Comment by mrglavas** [comment]
@aparnamichael I have discovered additional problems with the diagnostic classes and have opened a new issue https://github.com/OpenLiberty/liberty-tools-intellij/issues/879 to investigate and resolve them.
