### ISSUE TITLE
Update to latest LCLS release when available

### ISSUE THREAD

**Issue by TrevCraw** [OpenLiberty/liberty-tools-intellij#620]
Test with LCLS snapshot drivers when available: https://github.com/OpenLiberty/liberty-language-server

Update to final release version once integration is successful.

Check for any regressions in LCLS behaviour and test out the new behaviour provided by the new release.

**Comment by turkeylurkey** [comment]
Tested the 2.1.2 driver. Tested multiple features different versions message, XML directory support and increased hover info for features. All OK.
