### ISSUE TITLE
Fail to account for prefix during completion in properties file

### ISSUE THREAD

**Issue by turkeylurkey** [OpenLiberty/liberty-tools-intellij#622]
After you type a prefix and ctrl-space for completion the result adds the item selected but it adds it to the prefix you just typed so some letters appear twice.

![image](https://github.com/OpenLiberty/liberty-tools-intellij/assets/24705144/39887e61-37cb-440f-a5dd-23f9181098df)

**Comment by turkeylurkey** [comment]
In server.env there is a similar issue:
![image](https://github.com/OpenLiberty/liberty-tools-intellij/assets/24705144/060daea3-2b89-425c-982e-853e53d9566c)

**Comment by angelozerr** [comment]
Are you using our LSP4IJ (or aligning your LSP4IJ from ours)? I cannot reproduce the problem.

**Comment by turkeylurkey** [comment]
It happens when there is no text edit in the completion response.

**Comment by angelozerr** [comment]
Is it a snippet? If yes I suspect thatit is the same issue than https://github.com/redhat-developer/lsp4ij/issues/115 that I have fixed.

**Comment by angelozerr** [comment]
> This is the same issue as https://github.com/redhat-developer/lsp4ij/issues/91

I think soand the issue has been fixed, please align your LSP4IJ with our LSP4IJ.

Now we have User defined language server, it is very easy to test any language server with just a simple settings.

See my current PR which explains User defined language server https://github.com/redhat-developer/lsp4ij/pull/124

**Comment by turkeylurkey** [comment]
Latest tests show this is fixed in automated tests: 104 tests completed, 19 failed, 5 skipped down from 24 failed.
