### ISSUE TITLE
Invalid completion items appear in server.xml

### ISSUE THREAD

**Issue by turkeylurkey** [OpenLiberty/liberty-tools-intellij#624]
The prefix is typed but the correct choice is not offered in the test. Using server.xml in project singleModGradleMP in src/test/resources

![image](https://github.com/OpenLiberty/liberty-tools-intellij/assets/24705144/71cf5011-84ac-45f6-afa9-8ab76e12890e)

**Comment by TrevCraw** [comment]
may be same underlying issue as https://github.com/OpenLiberty/liberty-tools-intellij/issues/623
