### ISSUE TITLE
Catch and rethrow IndexNotReadyException, ProcessCanceledException and CancellationException

### ISSUE THREAD

**Issue by turkeylurkey** [OpenLiberty/liberty-tools-intellij#627]
When using lsp4ij the IDE may throw one of the subject exceptions. This must be caught and rethrown so that the operation can be retried. 

The idiom that causes trouble is:
```
try {
   <code that uses IntelliJ data>
} catch (Exception e) {
... 
}
```
We simply need to insert the lines 
```
catch (IndexNotReadyException | ProcessCanceledException | CancellationException e) { 
    throw e;
}
```

When the code in the try block uses only non-IntelliJ code such as java.util classes then this is not needed. Similarly if the catch block only catches specific exceptions like IOException then this is not needed.

This fix is made in many areas but we need to recheck after all the latest function branches are merged.

Sub tasks:
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/634
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/635

**Comment by mrglavas** [comment]
@TrevCraw @turkeylurkey Both of the sub-tasks are complete. Is there an additional review we intended to do here once everything has been merged on to main?

**Comment by TrevCraw** [comment]
@mrglavas For this particular issue, I don't think there is anything else to review.

**Comment by mrglavas** [comment]
Looks like I forgot to close this one. There's follow-up work for IntellIJ IDEA 2024.2 which is being tracked here: https://github.com/OpenLiberty/liberty-tools-intellij/issues/767.
