### ISSUE TITLE
Applying one quick fix results in the reversion of the previous one.

### ISSUE THREAD

**Issue by anusreelakshmi934** [OpenLiberty/liberty-tools-intellij#645]
When applying a quick fix, the corresponding diagnostic disappears. However, when a second quick fix is applied, the first fix is reverted. 
Subsequently, when a third quick fix is applied, both the first and second fixes are reverted. Repeating the application of quick fixes eventually results in all diagnostics disappearing.

I am in the branch [577-InsertAnnotationMissingQuickFix-new](https://github.com/anusreelakshmi934/liberty-tools-intellij/tree/577-InsertAnnotationMissingQuickFix-new) which is created from [code-action-unification-2](https://github.com/OpenLiberty/liberty-tools-intellij/tree/code-action-unification-2). To reproduce this issue, open the Jakarta Sample Project and the file `src/main/java/io/openliberty/sample/jakarta/persistence/MultipleMapKeyAnnotations.java` file. 
In the first case when applying quick fix to test1, the diagnostic is disappeared.
<img width="1100" alt="image" src="https://github.com/OpenLiberty/liberty-tools-intellij/assets/141303561/ec56e499-a15a-44f4-bc04-ea086821ee72">
<img width="592" alt="image" src="https://github.com/OpenLiberty/liberty-tools-intellij/assets/141303561/d0fa8377-3b56-449e-869c-39cceb2edc42">

But when next applying it to test2, the previous quick fix of test1 is reverted.
<img width="620" alt="image" src="https://github.com/OpenLiberty/liberty-tools-intellij/assets/141303561/93fd7b0e-5376-4aa7-b256-584bb2855bc8">

**Comment by TrevCraw** [comment]
1. Check if this problem is reproducible with other quick fixes
2. When able, check if this problem still persists using the latest LSP4IJ (current integration branch: https://github.com/OpenLiberty/liberty-tools-intellij/tree/useLSP4IJ1201)

**Comment by anusreelakshmi934** [comment]
> 1. Check if this problem is reproducible with other quick fixes
> 2. When able, check if this problem still persists using the latest LSP4IJ (current integration branch: https://github.com/OpenLiberty/liberty-tools-intellij/tree/useLSP4IJ1201)

The problem does not occur with other quick fixes. 
I attempted to reproduce the issue in the latest LSP4IJ integration branch but was unsuccessful. The problem is not present in this branch, as quick fixes are functioning properly.

**Comment by mrglavas** [comment]
Both @turkeylurkey and myself have been manually testing all of the Jakarta EE quick fixes including the specific diagnostics / quick fixes mentions in this issue. We have been unable to reproduce this issue.
