### ISSUE TITLE
Review the descriptions of the language servers

### ISSUE THREAD

**Issue by turkeylurkey** [OpenLiberty/liberty-tools-intellij#671]
The language server descriptions appear in the file: src/main/resources/META-INF/lsp.xml

**Comment by mrglavas** [comment]
The initial description for the MicroProfile Language Server was derived from the description of the same server in the Quarkus Tools plug-in: https://github.com/redhat-developer/intellij-quarkus/blob/main/src/main/resources/META-INF/lsp4ij-quarkus.xml.

**Comment by turkeylurkey** [comment]
Here is how the console descriptions look when rendered:
![image](https://github.com/OpenLiberty/liberty-tools-intellij/assets/24705144/1924e50e-3a1d-43f2-b503-657194afebb3)
![image](https://github.com/OpenLiberty/liberty-tools-intellij/assets/24705144/c23b5e34-82c5-44b4-ac51-5f8654b839b9)
![image](https://github.com/OpenLiberty/liberty-tools-intellij/assets/24705144/a716f0bc-719b-4b88-8225-8feaa43acc6f)
![image](https://github.com/OpenLiberty/liberty-tools-intellij/assets/24705144/6835eb88-03f7-4dd9-b4f3-62f712c8a027)
As @mrglavas said, the MicroProfile description is derived from another location.

The same descriptions appear in the settings panel as well. E.g. 
![image](https://github.com/OpenLiberty/liberty-tools-intellij/assets/24705144/1c68fdfa-e2b4-4e72-812c-0c2a6e88ea38)

@mrglavas @TrevCraw @yeekangc please take a look.

**Comment by mrglavas** [comment]
@turkeylurkey Comparing the screenshots I noticed that there are links in the MicroProfile description. Reviewing `lsp.xml`, I can see that those links point back to the LSP4MP language server project and the MicroProfile website. Assuming that we want to keep those links in the description, I wonder if we should add similar links to each of the other language server descriptions for consistency.

**Comment by yeekangc** [comment]
For what're related to Liberty Config Language Server, we can pull from https://github.com/OpenLiberty/liberty-language-server and review with @cherylking and team.  We can mark one for "properties files" and the other for "XML configuration files" (or similar terms).

For LSP4Jakarta, we should use "Language Server for Jakarta EE" and we can indeed link out to the LSP4Jakarta project (https://github.com/eclipse/lsp4jakarta) as well as jakarta.ee.

For LSP4MP, technically, it should be "Language Server for MicroProfile" (for the language server itself).  Linking to microprofile.io isn't an issue.  "Tools for MicroProfile" is really the IDE plugin or extension that pulls down the language server for the IDE users.  I don't think there is one (for LSP4MP) for IntelliJ IDEA yet (and similarly for LSP4Jakarta).

**Comment by angelozerr** [comment]
Lsp4mp hosts the MicroProfile langage server so your link can reference the project mp ls stored in lsp4mp.

It il that I did in intellij quarkus if I remember.

The best thing to do should create a New intellij plugin extensible for MicroProfile that you and us could be bases.

But for the moment it il not in my priority since I m working hard to lsp4ij

**Comment by angelozerr** [comment]
For liberty ls technically it is not a langage server I think it is an extension of the lemminx language server, right?

**Comment by angelozerr** [comment]
> Here is how the console descriptions look when rendered:

Please note that I have the intention to update this UI to try to display the same thing than LS preferences.

I have improved this LS preferences to display information in several tabs and display mappings. 

![image](https://github.com/OpenLiberty/liberty-tools-intellij/assets/1932211/7e20a21f-93e8-4ef0-a061-7eaf11f37a93)

See https://github.com/redhat-developer/lsp4ij/blob/main/docs/UserGuide.md#language-servers-preferences for more screenshot

**Comment by angelozerr** [comment]
Just for your information, I have started to update the LSP console UI, here a demo:

![NewUIDetailLSPConsole](https://github.com/OpenLiberty/liberty-tools-intellij/assets/1932211/f822e43a-eb9e-4ef6-9098-60de471c8c99)

See my draft PR at https://github.com/redhat-developer/lsp4ij/pull/177
