### ISSUE TITLE
Maven compatibility with Liberty tools

### ISSUE THREAD

**Issue by nagzeal** [OpenLiberty/liberty-tools-intellij#677]
HI - I would like to know if there is any restriction of Maven version, to get Liberty working?

ERROR] Failed to execute goal io.openliberty.tools:liberty-maven-plugin:3.10:dev (default-cli) on project policy-view-services: The plugin io.openliberty.tools:liberty-maven-plugin:3.10 requires Maven 

version 3.8.6 -> [Help 1]

**Comment by TrevCraw** [comment]
Hi @nagzeal , thank you for your query. As of version `3.9` (released in October 2023), the Liberty Maven Plugin requires a minimum Maven version of `3.8.6`: https://github.com/OpenLiberty/ci.maven/releases/tag/liberty-maven-3.9
