### ISSUE TITLE
Incorrect message in the Gradle Run/Debug configuration editor

### ISSUE THREAD

**Issue by turkeylurkey** [OpenLiberty/liberty-tools-intellij#686]
When working on a Gradle Liberty project click Run menu > Edit Configurations. Select Liberty and click '+'
A run configuration appears and next to Liberty Project the path to the build.gradle appears.
Under that is the message "Specify custom parameters for the mvn liberty:dev command." This message should refer to the command 'gradlew libertyDev' or use a generic description.

<img width="686" alt="image" src="https://github.com/OpenLiberty/liberty-tools-intellij/assets/24705144/bb38317e-3646-4a57-844d-c2f735ab461e">

**Comment by TrevCraw** [comment]
Suggestion to reword the "Specify custom parameters for the mvn liberty:dev command." to something like:
- "Specify custom parameters for the dev mode start command."
- "Specify custom parameters for the Liberty start command."
