### ISSUE TITLE
Setup framework for automated integration tests

### ISSUE THREAD

**Issue by kathrynkodama** [OpenLiberty/liberty-tools-intellij#69]

**Comment by mezarin** [comment]
**Tooling for UI test automation:** 
After a search, https://github.com/JetBrains/intellij-ui-test-robot appears to be the only tool that meets our test requirements.
Intellij-ui-test-robot is an active project, the automation can be made to work with github actions, and, most importantly, the tool appears to have the APIs we need. 
A deeper dive is required to validate the above.
