### ISSUE TITLE
Liberty Start in directory with space in name

### ISSUE THREAD

**Issue by turkeylurkey** [OpenLiberty/liberty-tools-intellij#690]
When you use a project with a space in the name (e.g. "GrdEE91 app") then Liberty Start does not work:
![image](https://github.com/OpenLiberty/liberty-tools-intellij/assets/24705144/40c080a5-33b8-4db0-b9d7-db3611459cf8)

The cd has quotes but the gradlew needs quotes too.

**Comment by turkeylurkey** [comment]
Actually quotes don't work. May need to try backslash: dirname\ app

**Comment by TrevCraw** [comment]
As part of this issue, a test should be created to cover this scenario.
