### ISSUE TITLE
Bootstrap.properties suggestions not replacing initially typed values upon selection

### ISSUE THREAD

**Issue by anusreelakshmi934** [OpenLiberty/liberty-tools-intellij#701]
When using the bootstrap.properties file, pressing ctrl+space provides accurate suggestions. However, if we type any letter, suggestions appear below, and upon clicking them, they don't replace the initially typed value.
Attaching SS for reference.
![image](https://github.com/OpenLiberty/liberty-tools-intellij/assets/141303561/d37baa01-4582-4033-9419-53918f1bc370)

![image](https://github.com/OpenLiberty/liberty-tools-intellij/assets/141303561/d299afc2-3981-48c3-b4b5-36c43b72274e)

**Comment by TrevCraw** [comment]
@anusreelakshmi934 on which branch did you observe this behaviour?

**Comment by anusreelakshmi934** [comment]
> @anusreelakshmi934 on which branch did you observe this behaviour?

I'm not sure which branch I saw this in, but it's also observed in the main branch.

**Comment by TrevCraw** [comment]
Resolved by https://github.com/MicroShed/lsp4ij/pull/17 for MicroShed lsp4ij for 24.0.6 milestone.

Resolved by https://github.com/redhat-developer/lsp4ij/pull/276 for redhat-developer lsp4ij for 24.0.7 milestone.

**Comment by anusreelakshmi934** [comment]
Tested using the latest version of LSP4IJ and is no longer reproducible
