### ISSUE TITLE
LSP4iJ 2024/04/01 integration: No trace produced on LSP console.

### ISSUE THREAD

**Issue by mrglavas** [OpenLiberty/liberty-tools-intellij#718]
While investigating https://github.com/OpenLiberty/liberty-tools-intellij/issues/717 I wanted to have a look at the LSP message traffic but noticed that when I attempt to enable verbose trace no trace output is written to the LSP console. I'm curious if this is working with the current code at: https://github.com/redhat-developer/lsp4ij. Is there some configuration that we're missing or is incorrect in the `plugin.xml` on the branch?

![image](https://github.com/OpenLiberty/liberty-tools-intellij/assets/890521/f8d2fc56-5430-4643-89b0-7a35596850ab)
![image](https://github.com/OpenLiberty/liberty-tools-intellij/assets/890521/8fcf1333-11e0-4d8e-b565-d4338cc8f91a)

**Comment by angelozerr** [comment]
Please read doc at https://github.com/redhat-developer/lsp4ij?tab=readme-ov-file

You need to save tour settings with Save icon in the toolbar:

![image](https://github.com/OpenLiberty/liberty-tools-intellij/assets/1932211/6530a6b8-ecfd-44e1-88bd-f0521ced4449)

**Comment by mrglavas** [comment]
Thanks. That worked. I often miss controls in UIs that are not explicitly labelled.

**Comment by angelozerr** [comment]
> Thanks. That worked. I often miss controls in UIs that are not explicitly labelled.

Don't hesitate to create a PR to improve the UI with your idea.
