### ISSUE TITLE
LSP4iJ 2024/04/01 integration: Completion does not overwrite the key text in bootstrap.properties

### ISSUE THREAD

**Issue by turkeylurkey** [OpenLiberty/liberty-tools-intellij#729]
When the user types text to select one of the keys in bootstrap.properties it is not replaced when the user selects one of the choices.
![image](https://github.com/OpenLiberty/liberty-tools-intellij/assets/24705144/1b413e0c-5559-4603-b51f-13a2c8a2f4fa)

**Comment by turkeylurkey** [comment]
Fixed by https://github.com/MicroShed/lsp4ij/pull/16

**Comment by angelozerr** [comment]
Just one question, have you the same problem with microprofile-config.properties? 

I have tested quickly with our IJ Quarkus and we have not this problem.

The PR disable resolve completion, it is not the proper fix. If you have a problem with our LSP4IJ, please share your LSP trace. 

I have started to write completion tests at  https://github.com/redhat-developer/lsp4ij/tree/main/src/test/java/com/redhat/devtools/lsp4ij/features/completion to provide a robust completion without breaking something when completion code which is complex is updated.

For instance see https://github.com/redhat-developer/lsp4ij/blob/637cd63d3b36c7571904849a32da934c8161d0d0/src/test/java/com/redhat/devtools/lsp4ij/features/completion/ClojureCompletionTest.java#L24

It would be nice to have your LSP trace and have a test with your usecase and fix it correctly if needed.

Thanks for sharing your LSP trace.
