### ISSUE TITLE
Quick fix option is not working for Microprofile quickfix

### ISSUE THREAD

**Issue by aparnamichael** [OpenLiberty/liberty-tools-intellij#775]
We are getting diagnostics and quickfix, when we remove @liveness annotation. But when we select a quick fix option, fix is not coming in the file. Due to this UI automated test is failing. 
test name - testMPQuickFixInJavaFile()
Redhat LSP4IJ version - [0.0.1-20240518-012816](https://plugins.jetbrains.com/plugin/23257-lsp4ij/versions/nightly/541423)

https://github.com/OpenLiberty/liberty-tools-intellij/assets/114654953/f2f3c1f3-b3d1-4d89-9eaa-114522150fe0

**Comment by aparnamichael** [comment]
There is a  change in the `resolvecodeaction` method in the `QuarkusLanguageClient.java` file. (used JSONUtils from LSP4IJ)
Commit link :  [https://github.com/redhat-developer/intellij-quarkus/commit/0d3437ea656f66e2bd71d0b25b77ab0d224b1e42#diff-1c090f2e6f8d11299[…]f7d2d0f37597479d04a0e3](https://github.com/redhat-developer/intellij-quarkus/commit/0d3437ea656f66e2bd71d0b25b77ab0d224b1e42#diff-1c090f2e6f8d11299[%E2%80%A6]f7d2d0f37597479d04a0e3)
I made the same change in resolvecodeaction method in our MicroprofileLanguageClient.java. Now Mp quickfix is working.

**Comment by angelozerr** [comment]
@aparnamichael can we close https://github.com/redhat-developer/lsp4ij/issues/294 ?

**Comment by TrevCraw** [comment]
@angelozerr that is unrelated to this closed issue
