### ISSUE TITLE
Despite specifying the version, only the latest Marketplace version of Lsp4ij gets installed during buildPlugin.

### ISSUE THREAD

**Issue by anusreelakshmi934** [OpenLiberty/liberty-tools-intellij#793]
When running the `./gradlew buildPlugin` task with the version set to `def lsp4ijNightlyVersion = '0.0.1-20240518-012816'` in the build.gradle file, the resulting zip file is generated in build/distributions. However, upon attempting to install the zip file using "install plugin from disk," it installs the latest nightly build version from the marketplace, which is `0.0.2-20240530-012934`. But  when launching the extension using `runIde`, it correctly utilizes the specified version.

Attaching SS below When Installing the Zip file: we get version - 0.0.2-20240530-012934
<img width="963" alt="image" src="https://github.com/OpenLiberty/liberty-tools-intellij/assets/141303561/0d86647e-e2f4-40fa-b017-ea80d7ae8fdc">

When running the extension: we get version - 0.0.1-20240518-012816
<img width="944" alt="image" src="https://github.com/OpenLiberty/liberty-tools-intellij/assets/141303561/ac25c2d8-4a0b-44a7-85b4-80ee19cc3a0c">

The Branch I am working on - [useLSP4IJmarket_2024.1_intellij_Support](https://github.com/OpenLiberty/liberty-tools-intellij/tree/useLSP4IJmarket_2024.1_intellij_Support)

**Comment by mrglavas** [comment]
After a discussion with JetBrains we determined that this is working as designed. By default (through the Plugins UI), IntelliJ will install the latest compatible version of a plug-in from the Marketplace. LTI has no control over which version of LSP4iJ will be installed. See this discussion on LSP4iJ versioning: https://github.com/redhat-developer/lsp4ij/discussions/353 for more insights on this topic.
