### ISSUE TITLE
Hover fails in server.xml when using custom liberty config 

### ISSUE THREAD

**Issue by turkeylurkey** [OpenLiberty/liberty-tools-intellij#796]
When using a custom liberty configuration the hover information can fail to appear. Follow these steps using a gradle project.
 - In `build.gradle` add
 ```
liberty {
    server {
        configDirectory = file('myConfig')
        bootstrapPropertiesFile = file('myboots.properties')
        serverEnvFile = file('othername.env')
    }
}
```
 - Start the liberty server
 - Stop the liberty server
 - In the terminal window type `./gradlew clean`
 - Hover over elements in `server.xml` in the editor. No information appears. 
 - Remove the custom configuration in `build.gradle` and hover starts working again.

**Comment by turkeylurkey** [comment]
I don't know if this is intermittent at all but I tried it on VS Code and hover worked because it went back to using the default xsd. The hover message tells you the source of the information.

**Comment by anusreelakshmi934** [comment]
I attempted to reproduce this issue using the latest main branch but was unable to do so. After following the outlined steps, I was still able to retrieve the hover information successfully. Following a `gradle clean` and starting and stopping the server, it used `server-cached-24.0.0.10.xsd`, and the hover information was accessible. When starting the server, it utilized `ol-24.0.0.11.xsd`. A screen recording is attached below. I tested both with and without renaming the config directory.

Without renaming the config directory.
https://github.com/user-attachments/assets/90512ecf-9af4-4059-94aa-1b49bb16c9d4

With renaming the config directory.
https://github.com/user-attachments/assets/cb4806f7-96e9-407e-ba1a-59b246b9363a

@turkeylurkey could you verify this?

**Comment by turkeylurkey** [comment]
I was not able to reproduce this either. It is possible LCLS fixed it.
