### ISSUE TITLE
Document how to manually install specific releases of LSP4iJ from the Marketplace.

### ISSUE THREAD

**Issue by mrglavas** [OpenLiberty/liberty-tools-intellij#816]
There may be good reasons that a user will want to use an older version of LSP4iJ (e.g. the exact version of LSP4iJ that was tested with LTI) and we should document how they can manually install that as a dependency from the Marketplace, including a link to the download page and instructions how to apply it in the IDE.

**Comment by TrevCraw** [comment]
Added as part of https://github.com/OpenLiberty/liberty-tools-intellij/pull/990
