### ISSUE TITLE
Hover message is randomly blank or there is a helpful message

### ISSUE THREAD

**Issue by turkeylurkey** [OpenLiberty/liberty-tools-intellij#844]
Sometimes an empty result is displayed when I hover in a properties file. Other times we see helpful content but there is a second page which is blank. I opened an issue to track this in [lsp4ij](https://github.com/redhat-developer/lsp4ij/issues/390).

This issue found while working on #760. testMicroProfileConfigHover() was failing due to empty description in hover. For more details scroll to the bottom of issue 760.

**Comment by turkeylurkey** [comment]
I believe this is fixed on the 0618 version of lsp4ij. If we move up to that level we can close this issue.

**Comment by TrevCraw** [comment]
Hi @aparnamichael , can you please update the `lsp4ij-market-0.0.2-integration` feature branch to use the LSP4IJ stable version `0.0.2` and then test to see if this is still an issue?

@turkeylurkey please also follow up using the updated feature branch.

**Comment by aparnamichael** [comment]
I have tested in my local with 0.0.2 stable version. In that there is only 1 page and documentation is coming as expected.

![0 0 2-hover-description](https://github.com/OpenLiberty/liberty-tools-intellij/assets/114654953/8ee28b45-d621-4c37-b685-b5ba30783628)

**Comment by aparnamichael** [comment]
@TrevCraw @turkeylurkey I have updated the lsp4ij-market-0.0.2-integration branch with lsp4ij 0.0.2 version.

**Comment by turkeylurkey** [comment]
I concur, I don't see the failure anymore either.

**Comment by TrevCraw** [comment]
@aparnamichael @turkeylurkey Thank you both for verifying!

I opened https://github.com/OpenLiberty/liberty-tools-intellij/issues/850 to cover adding a new automated test for this bug in the future. This issue can be closed.
