### ISSUE TITLE
IntelliJ 2024.2: Investigate on new change in remote robot

### ISSUE THREAD

**Issue by aparnamichael** [OpenLiberty/liberty-tools-intellij#885]
![image](https://github.com/user-attachments/assets/196e3839-aba1-481a-8e29-044c08ac5296)

Link to Slack message: https://jetbrains-platform.slack.com/archives/C05C80200LS/p1721452692806359

**Comment by TrevCraw** [comment]
Part of the investigation should involve looking into what `1.x` refers to and understanding if we need to move on from it.

**Comment by vaisakhkannan** [comment]
@aparnamichael, I identified that `1.x` refers to the `Gradle IntelliJ` version, and we want to migrate to the `IntelliJ Platform Gradle Plugin 2.x` as part of upgrading to` IntelliJ version 2024.2`.
After migrating to` 2.x`, we should update `runIdeForUiTests` accordingly as mentioned this way https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-migration.html#runideforuitests

**Comment by vaisakhkannan** [comment]
@TrevCraw ,Below is the code block that we require for running the `runIdeForUiTests` task.

```
intellijPlatformTesting.runIde {
    runIdeForUiTests {
        task {
            jvmArgumentProviders.add({
                [
                        "-Drobot-server.port=8082",
                        "-Dide.mac.message.dialogs.as.sheets=false",
                        "-Djb.privacy.policy.text=<!--999.999-->",
                        "-Djb.consents.confirmation.enabled=false",
                        "-Didea.trust.all.projects=true",
                        "-Dide.show.tips.on.startup.default.value=false",
                        "-Dide.mac.file.chooser.native=false",
                        "-DjbScreenMenuBar.enabled=false",
                        "-Dapple.laf.useScreenMenuBar=false",
                ]
            } as CommandLineArgumentProvider)
        }
        plugins {
            robotServerPlugin(remoteRobotVersion)
        }
    }
}
```

I can open PR for this soon

**Comment by vaisakhkannan** [comment]
Check the build that enabled `runIdeForUiTests` Task : https://github.com/vaisakhkannan/liberty-tools-intellij/actions/runs/11741958620
Branch : https://github.com/vaisakhkannan/liberty-tools-intellij/tree/refs/heads/%23885-Enable-runIdeForUiTests-task
