### ISSUE TITLE
Cron Job Builds are Taking PRs with Merge Conflicts

### ISSUE THREAD

**Issue by vaisakhkannan** [OpenLiberty/liberty-tools-intellij#889]
During testing, I used my forked repo's API to test with multiple open PRs as part of a cron job build tests. I found an issue where the cron job builds are taking PRs with merge conflicts.

https://github.com/vaisakhkannan/liberty-tools-intellij/actions/runs/10091019128

PR number 31 is the only PR which do not having merge conflicts. But Cron Job builds taking all the PRs.

Upon further inspection of the API, I discovered that there are several other values present for `mergeable_state`.

![image](https://github.com/user-attachments/assets/295ba6b4-13d8-4641-be67-bc118b50c28b)

**Comment by vaisakhkannan** [comment]
@TrevCraw ,
 
 As part of testing, I found that `mergeable` can be `null`. I am getting it in my fork repo API as shown in the image below
 
<img width="477" alt="Screenshot 2024-07-26 at 4 49 07 PM" src="https://github.com/user-attachments/assets/e7c07efc-ebbe-42a8-b8ba-3de230d4426b">

When I checked in the documentation [here ](https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#get-a-pull-request)
 
 
` The value of the mergeable attribute can be true, false, or null. If the value is null, then GitHub has started a background job to compute the mergeability. After giving the job time to complete, resubmit the request. When the job finishes, you will see a non-null value for the mergeable attribute in the response. If mergeable is true, then merge_commit_sha will be the SHA of the test merge commit.`

But this issue only occurs in my repo's API, so it might be specific to my repo. When I tested with the APIs of `lsp4ij, Liberty-tools-Intellij, Liberty-tools-vscode, and Anusree's forked repo`, I got the `expected` result. Therefore, I think this is a `rare` case.

So based on the above I have added in the [PR here](https://github.com/OpenLiberty/liberty-tools-intellij/pull/890/files)

Then I have investigated little bit on how to avoid getting null value for `mergeable` attribute ,then I found that 

Sometimes, the `mergeable` status isn't immediately available. We can implement a retry mechanism to wait until the status is no longer **null**.

Like the below code , we can add some `wait` to confirm the `mergeable` status is no longer `null`


```
mergeable=null
attempts=0
max_attempts=5

# Retry loop for checking mergeability
while [[ "$mergeable" == "null" && $attempts -lt $max_attempts ]]; do
  pr_detail=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "$url")
  echo "PR Detail (Attempt $((attempts+1))): $pr_detail"
  mergeable=$(jq -r '.mergeable' <<< "$pr_detail")
  echo "Mergeable: $mergeable"

  if [[ "$mergeable" == "null" ]]; then
    echo "Mergeable status is null, retrying in 5 seconds..."
    sleep 5
  fi

  attempts=$((attempts + 1))
done

```

When I discussed this with the Kochi team, we concluded that the problem only exists in my forked repository and is working fine in the `lsp4ij repository`. Therefore, we don't need to add `wait` or checking the condition in loop for the `mergeable` state. I also think this is acceptable since it's a rare case in the API. What do you think? 
Based on our current discussion, I have updated the PR.

**Comment by TrevCraw** [comment]
Hi @vaisakhkannan , after a discussion with @mrglavas and @turkeylurkey , this is our feedback:

- It does not hurt to include the wait to check if the `mergeable` `null` value switches to `true`. There is nothing really waiting on these builds. 
  - Initial suggestion is to wait for a total of 10 minutes with a check every minute.
  - It would be ideal if the new "wait and check" code could be placed in a spot where it does not block other builds from running that have mergeable PRs.
- We should go ahead and still run the build if `mergeable` remains `null`. However, there is one condition: if the build fails, it must be up front and clear to the build reviewer that the mergeability of the PR was `null`. We don't want someone to spend time investigating the build failure of a PR in a `mergeable` `null` state.

**Comment by vaisakhkannan** [comment]
Hi @TrevCraw , Based on your suggestions, I have updated the [PR](https://github.com/OpenLiberty/liberty-tools-intellij/pull/890/files). The changes are not exactly as you suggested but are similar to the code I shared above. I don't think we need to wait for 10 minutes and check the condition in every minute. Instead, I am checking the `mergeable` value. If the value is null, it sleeps for `5 seconds `and checks again. This loop continues based on the `max_attempts` variable. During my testing, I was able to get a true or false value for the `mergeable` variable on `second` attempt , so I think it's okay to set a value for `max_attempts` as `5`.

Therefore, we don't need to add new "wait and check" code, nor do we need to check whether it blocks builds of `mergeable PRs`. There is no need additional code to check for other conditions.

With the new changes, we are checking the conditions up to `5 times`. If the value is still `null`, it won't take those PRs. Instead, it will take PRs that have `mergeable` value as `true`. If required, we can increase the value of `max_attempts`. I haven't encountered any cases that require a `max_attempts` value greater than 5, so I believe it's okay to stay with a value of 5.

<img width="999" alt="Screenshot 2024-07-30 at 3 38 45 PM" src="https://github.com/user-attachments/assets/f329d77c-5b2d-40d2-a140-bd871487eb4a">

Reference links for the tests run:
https://github.com/vaisakhkannan/liberty-tools-intellij/actions/runs/10158451647/job/28090543073

https://github.com/vaisakhkannan/liberty-tools-intellij/actions/runs/10158609832/job/28091034094

https://github.com/vaisakhkannan/liberty-tools-intellij/actions/runs/10158309585/job/28090096752
