### ISSUE TITLE
Outdated 'rustup' Installation

### ISSUE THREAD

**Issue by vaisakhkannan** [OpenLiberty/liberty-tools-intellij#892]
While running the builds we are getting the below warning messages for the component `rustup`

`rustup is outdated! To avoid broken installations, as soon as possible please run: brew upgrade Or, if you're OK with a less reliable fix: brew upgrade rustup`

**Comment by vaisakhkannan** [comment]
Screenshot of Error:
<img width="1261" alt="Screenshot 2024-07-31 at 2 48 19 PM" src="https://github.com/user-attachments/assets/3c189ca8-d12e-426f-957c-4ce96184fc41">

**Comment by vaisakhkannan** [comment]
@mrglavas  , @aparnamichael 

This warning is no longer occurring after testing with the changes in the PR - https://github.com/OpenLiberty/liberty-tools-intellij/pull/903

Link for Reference : 
https://github.com/vaisakhkannan/liberty-tools-intellij/actions/runs/10269828563/attempts/1
https://github.com/vaisakhkannan/liberty-tools-intellij/actions/runs/10265977884
https://github.com/vaisakhkannan/liberty-tools-intellij/actions/runs/10246543757

**Comment by mrglavas** [comment]
@vaisakhkannan It sounds like https://github.com/OpenLiberty/liberty-tools-intellij/pull/903 also resolves this issue. You should mention that in the PR. This issue can be closed once you merge the PR.

**Comment by vaisakhkannan** [comment]
Closing this issue , since it not reproducible with the changes in the feature branch after merging the PR #903
