### ISSUE TITLE
Documentation for developers to understand continuous build integration 

### ISSUE THREAD

**Issue by anusreelakshmi934** [OpenLiberty/liberty-tools-intellij#896]
Provide information on how to interpret the build results, including details about artifact names and webhooks. 
Explain the build results and the outcomes of the lsp4ij cron job.

- [ ]  Document the workflow of normal build.yaml execution (PR/Push build execution). - Anusree - In Review
- [ ]  Document how Cron Job builds are executed with respect to build.yaml builds. - Anusree - In Review
- [ ] Document Testing against a Specific Version of LSP4IJ - Anusree - In Review
- [ ]  Document how Slack notifications are triggered based on LSP4IJ PR lists --> Vaisakh - In Review
- [ ]  Document how build results are posted to the Slack channel --> Vaisakh - In Review
- [ ]  Explain how secrets and webhook URLs can be added to the LTI repo/forked repo --> Vaisakh  - In Review
- [ ] Explanation of Slack Messages for Build Results and Listing LSP4IJ PRs --> Vaisakh - In Review
- [ ] Document how to configure and Edit Slack Workflow Builder --> Vaisakh - In Review
- [ ] Document how we can specify Existing LTI Tag or branches to CI/CD builds --> Vaisakh - In Review

**Comment by aparnamichael** [comment]
@anusreelakshmi934 I have reviewed the documentation in Box Note and added a few comments. Please take a look.

**Comment by aparnamichael** [comment]
@anusreelakshmi934 @vaisakhkannan I have completed reviewing the documentation in Box Note and added a few comments. Please take a look.

**Comment by aparnamichael** [comment]
@vaisakhkannan @anusreelakshmi934 I have reviewed the documentation again after both of you addressed my feedback, and everything looks good.

**Comment by anusreelakshmi934** [comment]
[LSP4IJ-Continuous-Integration Doc](https://github.com/OpenLiberty/liberty-tools-intellij/blob/main/docs/LSP4IJ-Continuous-Integration.md)
