### ISSUE TITLE
Warnings in GitHub Workflows on macOS 14.6 for curl Version 8.9.1

### ISSUE THREAD

**Issue by vaisakhkannan** [OpenLiberty/liberty-tools-intellij#902]
I found the following warning in Mac builds (specifically in the step to install required integration test software).

`curl 8.9.1 is already installed and up-to-date. To reinstall 8.9.1, run: brew reinstall curl`

<img width="954" alt="Screenshot 2024-08-06 at 8 06 56 PM" src="https://github.com/user-attachments/assets/af5b3ba3-3b89-44fc-bfb2-2c75d2aa9a36">

When I checked this issue, I found that this warning occurs only on GHA Mac machines with OS version 14.6 and not on 14.5.

Here is an example of a workflow run: https://github.com/vaisakhkannan/liberty-tools-intellij/actions/runs/10266055640
(  Warning came only in the `main` branch, PR number `19`, and PR number `11`. Those Mac builds were run on macOS version `14.6` and others are were run on Mac OS version `14.5`)

**Comment by vaisakhkannan** [comment]
@mrglavas 

 found this warning only on GHA Mac OS build 14.6, not on Mac OS 14.5. Therefore, we will encounter this warning in rare cases. Should we investigate the possibility of avoiding this warning now?

**Comment by mrglavas** [comment]
> @mrglavas
> 
> found this warning only on GHA Mac OS build 14.6, not on Mac OS 14.5. Therefore, we will encounter this warning in rare cases. Should we investigate the possibility of avoiding this warning now?

@vaisakhkannan Is this really a rare case? I saw this warning in each of the four builds you linked here: https://github.com/OpenLiberty/liberty-tools-intellij/pull/903#issuecomment-2277628596? I think it's worth investigating if there's some way we can resolve it to further reduce the noise in the build results.

**Comment by vaisakhkannan** [comment]
@mrglavas, 
I found that they made the changes 4 days ago. During my initial testing, which was 4 days ago, I was getting macOS versions 14.5 and 14.6, and the warnings were only found in 14.6. Now, it only gets macOS version 14.6 when we specify the macOS platform as macOS-latest.


https://github.com/actions/runner-images/commit/3a24d66b9e28cd87d24f1fed3c9d849e337982f6 --> Commit history of macos-latest version 14.6 in their documentation 
https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md --> Currently using macos-latest version 14.6

**Comment by vaisakhkannan** [comment]
Based on the discussion with Trevor , we may use other macOS platforms to run tests on GHA in the future. Some earlier versions of macOS do not have curl installed by default or may have an outdated version of curl. The warning mentioned in this issue only appears if curl is already installed and up-to-date on the Mac machine. Therefore, it’s a good idea to suppress this warning now. There is no difference in working with this change.
