### ISSUE TITLE
The start command intermittently fails to execute after the cd command.

### ISSUE THREAD

**Issue by aparnamichael** [OpenLiberty/liberty-tools-intellij#910]
Timeput exception in while executing UI test - **Timed out while waiting for project with resource URI api/resourceand port 9080 to become available.**

![356215837-a12817a9-1ade-4744-898d-133194dc32d1](https://github.com/user-attachments/assets/f44ea6a8-3d77-403e-b4c3-e5311cc66824)

**Comment by vaisakhkannan** [comment]
This issue is no longer occurring in Windows GHA builds or locally.
LTI version : 24.0.9
LSP4IJ version : 0.6.0

Reference: https://github.com/vaisakhkannan/liberty-tools-intellij/actions/runs/11149154355/attempts/2

Closing this issue since its no longer occurring
