### ISSUE TITLE
IntelliJ 2024.2: Migrate to IntelliJ Platform Gradle Plugin 2.x

### ISSUE THREAD

**Issue by TrevCraw** [OpenLiberty/liberty-tools-intellij#911]
As mentioned in Slack communication in the JetBrains Slack channel, plugins targeting 2024.2 must migrate from Gradle IntelliJ 1.x to IntelliJ Platform Gradle Plugin 2.x

More information on the migration can be found here: https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-migration.html

Link to Slack message: https://jetbrains-platform.slack.com/archives/C5U8BM1MK/p1721656635063899

**Comment by staicy123** [comment]
Hi @TrevCraw,
Here I am attaching the commit with all the changes made to support 2024.2 version in my forked feature branch. I have completed FVT for 2024.2 with java version 17 gradle and once I complete the FVT for 2024.2 with java version 21 and 2024.1 java version 17. I will raise the PR for the same. https://github.com/OpenLiberty/liberty-tools-intellij/compare/main...staicy123:liberty-tools-intellij:%23911-Migrate-Gradle-Plugin-2.x-intellij-2024.2?expand=1
Thanks

**Comment by staicy123** [comment]
Hi @TrevCraw, 
PR raised for the change here: https://github.com/OpenLiberty/liberty-tools-intellij/pull/1053.
Please review and share your comments.

Thanks

**Comment by staicy123** [comment]
Hi @TrevCraw ,
I have updated the PR with all the changes required for supporting 2024.2 intellij version for running buildPlugin task.
https://github.com/OpenLiberty/liberty-tools-intellij/pull/1053
Unit test discussed here: https://github.com/OpenLiberty/liberty-tools-intellij/issues/1048 (Needs to be fixed from jetbrains end)
Ui test:
Two issues needs to be addressed for this one 

1. https://github.com/OpenLiberty/liberty-tools-intellij/issues/1088 (Started the analysis)
2. https://github.com/OpenLiberty/liberty-tools-intellij/issues/1018 (In progress fixing test failures)

The PR for  runIdeForUiTests task supporting intellij 2024.2 change in build.gradle will be raised by @vaisakhkannan once my changes are reviewed and merged.

Thanks

**Comment by staicy123** [comment]
The changes have been successfully merged. Therefore, this ticket will be closed.
