### ISSUE TITLE
Update to LSP4IJ version 0.4.0

### ISSUE THREAD

**Issue by TrevCraw** [OpenLiberty/liberty-tools-intellij#914]
- [x] Run automated tests with LSP4IJ 0.4.0 release candidate
- [x] Manually test with LSP4IJ 0.4.0 release candidate
- [x] Create new LSP4IJ integration feature branch based off of the lsp4ij-market-0.3.0-integration branch named lsp4ij-market-0.4.0-integration
- [x] Update default version specified in build.gradle to 0.4.0 once it has been released

**Comment by anusreelakshmi934** [comment]
Ran the automated tests with the latest `0.4.0-20240813-173701 nightly` version- https://github.com/anusreelakshmi934/liberty-tools-intellij/actions/runs/10382367736
