### ISSUE TITLE
LS Integration: Narrow activation scope of LS for Liberty server configuration

### ISSUE THREAD

**Issue by kathrynkodama** [OpenLiberty/liberty-tools-intellij#92]
Currently the liberty-langserver activates on any files named `bootstrap.properties` or `server.env`. We should narrow this scope to only activate on these files in certain directory structures:

bootstrap.properties - File named "bootstrap.properties" and exists in either a "src/main/liberty/config" or "usr/servers" directory

server.env - File named "server.env" and exists in either a "src/main/liberty/config" or "usr/servers" directory

**Comment by evie-lau** [comment]
So far I've only found this [issue discussion page](https://youtrack.jetbrains.com/issue/IDEA-107807/Dynamic-File-Type-Patterns) asking for the same thing, to allow matches to include directories and not just filename. 9 year old discussion, and as far as I can find, is still an open request to support it.

**Comment by evie-lau** [comment]
Kathryn shared [this article](https://www.plugin-dev.com/intellij/custom-language/file-type-detection/) which shows an implementation to check directory. Currently investigating, but it looks like the cornerstone is the [FileTypeFactory](https://github.com/JetBrains/intellij-community/blob/idea/222.4345.14/platform/ide-core/src/com/intellij/openapi/fileTypes/FileTypeFactory.java) class which was deprecated in 2019 in favor of [FileType](https://github.com/JetBrains/intellij-community/blob/idea/222.4345.14/platform/core-api/src/com/intellij/openapi/fileTypes/FileType.java), which does not seem to support filtering by directory.
