### ISSUE TITLE
Custom start is getting stuck while trying to access messages.log

### ISSUE THREAD

**Issue by aparnamichael** [OpenLiberty/liberty-tools-intellij#929]
While running custom start tests, inconsistently getting stuck at the same step.

org.opentest4j.AssertionFailedError: testStartWithConfigInRunModeUsingMenu:validateLibertyServerStopped: Exit. Timed out waiting for message CWWKE0036I in log:D:\a\liberty-tools-intellij\liberty-tools-intellij\liberty-tools-intellij\src\test\resources\projects\maven\singleModMavenMP\target\liberty\wlp\usr\servers\defaultServer\logs\messages.log 

![image](https://github.com/user-attachments/assets/42f2d607-7a8f-4228-9b4b-0b0092827689)

***Note: This error is occurring with other tests as well, running in Windows. Refer to https://github.com/OpenLiberty/liberty-tools-intellij/actions/runs/10592982820/job/29362112582?pr=932

**Comment by aparnamichael** [comment]
The same timeout issue is present in Linux builds as well, the server is not starting within the 90 seconds timeout. When we increase the timeout all the tests are passing.

**Comment by anusreelakshmi934** [comment]
We weren't able to gather much additional information from the terminal log captures; the output was similar to what we typically see in the GHA builds. Despite increasing the timeout to 10 minutes, a few tests are still failing—about 1 in 10—mirroring the failure rate seen without any fixes.

Here are the different methods we've tried to stop the server after each test:
- Closing the terminal after each test.
- Killing the port after each test.
- Running `mvn/gradle clean` after each test.
- Running `mvn/gradle liberty:stop` and closing all terminal tabs after each test.

**Comment by anusreelakshmi934** [comment]
By running mvn liberty:stop and gradle libertyStop after each test, and closing the terminal after each test the following results were obtained - https://github.com/anusreelakshmi934/liberty-tools-intellij/actions/runs/11330115163/job/31507206058. 
From the videos of these failed tests, we can confirm that the delay in liberty server is not just for starting. but also here while running gradle liberty stop also is not executed completely. it is also facing delay to get complete hence the next test fails.

**Comment by anusreelakshmi934** [comment]
We ran `mvn liberty:stop`/`gradle libertyStop` after each test by opening a new terminal, then closed all open terminal tabs. Next, we opened a new terminal to run `mvn`/`gradle clean` and again closed all open terminal tabs. Following this approach, we are now getting successful (green) builds.

**Comment by turkeylurkey** [comment]
Same as #428. Should close that one.
