### ISSUE TITLE
Resolve Warnings from the pr-slack-notification.yaml Cron Job Builds

### ISSUE THREAD

**Issue by vaisakhkannan** [OpenLiberty/liberty-tools-intellij#937]
Warnings were found in the pr-slack-notification.yaml cron job builds.

<img width="1211" alt="Screenshot 2024-08-30 at 2 00 44 PM" src="https://github.com/user-attachments/assets/53d697e2-4153-4295-bdc2-0226af4cb003">

LInk to example GitHub Action --> https://github.com/anusreelakshmi934/liberty-tools-intellij/actions/runs/10618252957

**Comment by vaisakhkannan** [comment]
To resolve this issue, update the version from `v2` to `v4` for the following occurrences in the `pr-slack-notification.yaml` file.

https://github.com/OpenLiberty/liberty-tools-intellij/blob/2974544203bbc55462e64d0c320b6f09633c86a7/.github/workflows/pr-slack-notification.yaml#L23

https://github.com/OpenLiberty/liberty-tools-intellij/blob/2974544203bbc55462e64d0c320b6f09633c86a7/.github/workflows/pr-slack-notification.yaml#L47

https://github.com/OpenLiberty/liberty-tools-intellij/blob/2974544203bbc55462e64d0c320b6f09633c86a7/.github/workflows/pr-slack-notification.yaml#L236

**Comment by vaisakhkannan** [comment]
I have tested the changes after updating from version `v2` to `v4`. The changes look good to me. Below are examples of the workflow runs.

https://github.com/vaisakhkannan/liberty-tools-intellij/actions/runs/10627523978

https://github.com/vaisakhkannan/liberty-tools-intellij/actions/runs/10627514571

**Comment by vaisakhkannan** [comment]
@TrevCraw 
Since we already opened a PR from the feature branch to main, do we need to wait for the feature branch to be merged into main, and then open another PR to main to resolve this issue?

**Comment by TrevCraw** [comment]
Hi @vaisakhkannan , thank you for finding and fixing this. Yes, let's wait until the feature branch is merged and then open a PR for this issue directly against the main branch.
