### ISSUE TITLE
Move up to Java 17 support

### ISSUE THREAD

**Issue by kathrynkodama** [OpenLiberty/liberty-tools-intellij#96]
See https://github.com/OpenLiberty/liberty-tools-eclipse/issues/166

**Comment by kathrynkodama** [comment]
Included as part of this issue, we should try and launch the language servers with Java 17. If possible, deliver a helpful error/warning message if Java 17 is not found

**Comment by TrevCraw** [comment]
As part of this issue, we should confirm what steps users are required to take to run our plugin once it is installed. For instance, do they need to configure Java 17 somewhere in their IntelliJ settings?
