### ISSUE TITLE
FVT 24.0.9 -In server.xml, the feature still appears in the snippet suggestions, even though the feature is already present in the file.

### ISSUE THREAD

**Issue by aparnamichael** [OpenLiberty/liberty-tools-intellij#965]
In server.xml, the feature still appears in the snippet suggestions, even though the feature is already present in the file.

We've added the 'appAuthentication' feature to server.xml and when we type 'app,' 'appAuthentication' still appears in the suggestion list.

![image](https://github.com/user-attachments/assets/5d2cb80a-3775-45cb-87c7-ccc9c194c803)

**Comment by dessina-devasia** [comment]
Tested the mentioned issue using LCLS 2.2-SNAPSHOT in LTI. Issue has been resolved.

![image](https://github.com/user-attachments/assets/a528dcf8-0dc6-404f-940e-5236ee062560)

**Comment by JoshwinThomasIBM** [comment]
issue is resolved with LCLS 2.2-snapshot in LTV 

<img width="807" alt="image" src="https://github.com/user-attachments/assets/eb5b6ec7-a708-4e89-bde3-64cc9195c742">

<img width="657" alt="image" src="https://github.com/user-attachments/assets/557052ca-1b8e-4571-a539-39cd3b90794e">

**Comment by TrevCraw** [comment]
@JoshwinThomasIBM please report LTV update in https://github.com/OpenLiberty/liberty-tools-vscode/issues/342
