### ISSUE TITLE
FVT 24.0.9 -In server.xml, the diagnostics is not displaying when the same feature is added again.

### ISSUE THREAD

**Issue by aparnamichael** [OpenLiberty/liberty-tools-intellij#966]
I added both 'servlet' and 'servlet-3.1', but the diagnostics aren't showing.
Tested this in VS Code, and the diagnostics is showing for duplicate feature in the VS Code IDE.

![image](https://github.com/user-attachments/assets/d4af44f8-4a8b-4d6a-90c3-814cae356748)

**Comment by dessina-devasia** [comment]
Tested the case by using LCLS 2.2-SNAPSHOT. Diagnostics and quick fix for the incorrect feature can be identified indicates it supports the versionless feature.

![image](https://github.com/user-attachments/assets/9d1283bf-6574-48c5-9b00-3781fa24a6a2)

**Comment by dessina-devasia** [comment]
Diagnostics related to adding the same feature multiple times are functioning correctly with LCLS 2.2-SNAPSHOT.

![image](https://github.com/user-attachments/assets/e74a1482-a180-4a75-8f54-42d0f73de4c7)

**Comment by JoshwinThomasIBM** [comment]
LCLS 2.2-snapshot LTV

Received the diagnostics and quick fixes when the version less feature is added 
<img width="1234" alt="image" src="https://github.com/user-attachments/assets/66087908-e5e9-49d7-abff-28022067219b">

Also received the diagnostics when same feature is added multiple times
<img width="1084" alt="image" src="https://github.com/user-attachments/assets/d8111332-3e4b-4777-a9f3-41a01a4b0369">

**Comment by TrevCraw** [comment]
Hi @JoshwinThomasIBM , please report LTV updates in the LTV repo: https://github.com/OpenLiberty/liberty-tools-vscode.

For LTV LCLS support updates, they can be posted here: https://github.com/OpenLiberty/liberty-tools-vscode/issues/342
