### ISSUE TITLE
LS integration: serverInterface tag bug

### ISSUE THREAD

**Issue by kathrynkodama** [OpenLiberty/liberty-tools-intellij#97]
Currently the `serverInterface` tag defined in `lsp.xml` only works if set to `org.eclipse.lsp4mp.ls.api.MicroProfileLanguageServerAPI` regardless of the language server being started.
Changing the server interface to the corresponding ServerAPI class, ie. `org.eclipse.lemminx.customservice.XMLLanguageClientAPI` causes a ClassCastException. 

See https://github.com/OpenLiberty/liberty-tools-intellij/blob/11f80ed87be9625abb80d11618e8a60be93afa37/src/main/resources/META-INF/lsp.xml#L17-L22

**Comment by anusreelakshmi934** [comment]
The `serverInterface` tag is removed from the lsp.xml file. Now we have `factoryClass` tag set to `io.openliberty.tools.intellij.liberty.lsp.LibertyXmlServerFactory`. 
See : 

https://github.com/OpenLiberty/liberty-tools-intellij/blob/a4857acddbf46b7b33d5cfc1f3185a4beb8bb8c8/src/main/resources/META-INF/lsp.xml#L31-L45
