### ISSUE TITLE
Unable to insert entry in config file : server.env in LINUX & Windows

### ISSUE THREAD

**Issue by anusreelakshmi934** [OpenLiberty/liberty-tools-intellij#988]
In Linux While running the UI Tests, In the test GradleSingleModLSTest > testInsertLibertyConfigIntoServerEnv() we are getting a failure.

Build link - https://github.com/anusreelakshmi934/liberty-tools-intellij/actions/runs/10953290952/job/30413321818#step:10:1120

GradleSingleModLSTest > testInsertLibertyConfigIntoServerEnv() FAILED
    java.lang.RuntimeException: Unable to insert entry in config file : server.env using text: WLP_LOGGING_CON

Attaching the failure video.

https://github.com/user-attachments/assets/4c4ca166-1a38-4cfa-b028-eaa79970c73a

The correct test should get suggestions while typing WLP_LOGGING_CON and should click on the suggestion given. But here it is not getting suggestions.

**Comment by turkeylurkey** [comment]
The Mac version: https://github.com/OpenLiberty/liberty-tools-intellij/issues/972

**Comment by turkeylurkey** [comment]
The Windows version: https://github.com/OpenLiberty/liberty-tools-intellij/issues/945

**Comment by turkeylurkey** [comment]
Similar Mac error: https://github.com/OpenLiberty/liberty-tools-intellij/issues/973

**Comment by turkeylurkey** [comment]
This is related to the hover test using the word NONE because they are in the same test case and both use the same language server.
<img width="446" alt="image" src="https://github.com/user-attachments/assets/45444914-4382-4745-b8f8-705f473b9e0a">
First we insert using completion and then type NONE to test hover.

**Comment by vaisakhkannan** [comment]
Found similar issue on Windows GHA Builds today: 

https://github.com/user-attachments/assets/86a34431-4ab1-4142-a833-d859fe7564e0

**Comment by anusreelakshmi934** [comment]
Closing the issue as a [fix](https://github.com/OpenLiberty/liberty-tools-intellij/pull/1051) has been merged, which resolves this problem. The issue is no longer reproducible.
